 
INSERT INTO  ski.targets(id_target ,name ,original_name ,description,notes,resource_url ) VALUES
    ( 1 , 'Jodan' ,$$Jodan$$ ,$$Alto$$ ,NULL ,NULL ),
    ( 2 , 'Chudan' ,$$Chudan$$ ,$$Medio$$ ,$$Poco sopra l'ombelico$$ ,NULL ),
    ( 3 , 'Gedan' ,$$Gedan$$ ,$$Basso$$ ,NULL ,NULL ),
    ( 4 , 'Testa' ,$$Atama$$ ,NULL ,NULL ,NULL ),
    ( 5 , 'Faccia' ,$$Kao$$ ,NULL ,NULL ,NULL ),
    ( 6 , 'Mascella' ,$$Ago$$ ,NULL ,$$Lato del volto sulla mascella$$ ,NULL ),
    ( 7 , 'Collo Laterale' ,$$Kubi$$ ,NULL ,NULL ,NULL ),
    ( 8 , 'Gola' ,$$Nodo$$ ,NULL ,NULL ,NULL ),
    ( 9 , 'Torace' ,$$Mune$$ ,NULL ,NULL ,NULL )
;

INSERT INTO ski.strikingparts(id_part, name, translation, description, notes, resource_url) VALUES 
    ( 1 , 'Seiken' ,NULL ,$$Nocche indice e medio$$ ,NULL ,NULL ),
    ( 2 , 'Koshi' ,NULL ,$$Radice delle dita dei piedi con dita alzate$$ ,NULL ,NULL ),
    ( 3 , 'Empi' ,$$Gomito$$ ,$$Gomito$$ ,NULL ,NULL ),
    ( 4 , 'Hirabasami' ,NULL ,$$incavo mano pollice indice$$ ,NULL ,NULL ),
    ( 5 , 'Kumade' ,NULL ,$$palmo della mano$$ ,NULL ,NULL ),
    ( 6 , 'Teisho' ,NULL ,$$palmo della mano all' attaccatura con l'avambraccio$$ ,NULL ,NULL ),
    ( 7 , 'Gaiwan' ,NULL ,$$Avambraccio dal lato esterno / ulna$$ ,NULL ,NULL ),
    ( 8 , 'Naiwan' ,NULL ,$$Avambraccio dal lato interno / radio$$ ,NULL ,NULL ),
    ( 9 , 'Haiwan' ,NULL ,$$Avambraccio lato superiore$$ ,NULL ,NULL ),
    ( 10 , 'Huraken' ,NULL ,$$Esterno della mano$$ ,NULL ,NULL ),
    ( 11 , 'Keito' ,NULL ,$$Radice del police$$ ,NULL ,NULL ),
    ( 12 , 'Kakuto' ,NULL ,$$polso esterno$$ ,NULL ,NULL ),
    ( 13 , 'Tetsui' ,NULL ,$$parte bassa del pungo$$ ,NULL ,NULL ),
    ( 14 , 'Washide' ,NULL ,$$Punta delle dita unite come a raccogliere$$ ,NULL ,NULL ),
    ( 15 , 'Nakadaka Ken' ,NULL ,$$Medio leggermente fuoriuscito dal pugno$$ ,NULL ,NULL ),
    ( 16 , 'Ippon Ken' ,NULL ,$$Indice leggermente fuoriuscito dal pugno$$ ,NULL ,NULL ),
    ( 17 , 'Hihon Nukite' ,NULL ,$$Punta di indice e medio protesi$$ ,NULL ,NULL ),
    ( 18 , 'Hiraken' ,NULL ,$$Falange intermedia della mano$$ ,NULL ,NULL ),
    ( 19 , 'Ippon Nukite' ,NULL ,$$Punta dell'indice proteso$$ ,NULL ,NULL ),
    ( 20 , 'Haito' ,NULL ,$$esterno della falange del pollice$$ ,NULL ,NULL ),
    ( 21 , 'Haishu' ,NULL ,$$Palmo esterno mano$$ ,NULL ,NULL ),
    ( 22 , 'Shuto' ,NULL ,$$Mano a taglio$$ ,NULL ,NULL ),
    ( 23 , 'Nukite' ,NULL ,$$punta delle dita estese ed unite $$ ,NULL ,NULL ),
    ( 24 , 'Sune' ,NULL ,$$tibbia$$ ,NULL ,NULL ),
    ( 25 , 'Hiza' ,NULL ,$$Ginocchio$$ ,NULL ,NULL ),
    ( 26 , 'Kakato' ,NULL ,$$Tallone$$ ,NULL ,NULL ),
    ( 28 , 'Sokuto' ,NULL ,$$Esterno del piede$$ ,NULL ,NULL ),
    ( 29 , 'teisoku' ,NULL ,$$Palmo del piede$$ ,NULL ,NULL ),
    ( 30 , 'Tsumashi' ,NULL ,$$Dita del piede$$ ,NULL ,NULL ),
    ( 31 , 'Heisoku' ,NULL ,$$Dorso del piede$$ ,NULL ,NULL )
;

INSERT INTO ski.technics(id_technic,waza ,name ,description ,notes ,resource_url ) VALUES
    ( 0 , 'NA' ,'Yoi',$$Posizione neutra ma pronta$$ ,$$Posizione di partenza neutra ma pronta per l'azione$$ ,NULL ),
    ( 1 , 'NA' ,'Guardia',$$$$ ,NULL ,NULL ),
    ( 2 , 'NA' ,'Kiri Kaeshi',$$Cambio guardia$$ ,NULL ,NULL ),
    ( 10 , 'Uchi' ,'Age tsuki',$$Pugno diritto che sale dal basso verso l'alto$$ ,NULL ,NULL ),
    ( 11 , 'Uke' ,'Age uke',$$Parata crescente verso l'alto$$ ,NULL ,NULL ),
    ( 12 , 'Geri' ,'Ashi barai',$$Spazzata$$ ,NULL ,NULL ),
    ( 13 , 'Uchi' ,'Awase tsuki',$$Pugni a U piccola (eseguiti colpendo contemporaneamente il bersaglio alto con Choku tsuki e quello medio con Ura tsuki)$$ ,NULL ,NULL ),
    ( 14 , 'Uchi' ,'tsuki',$$Pugno sferrato verso la parte media del corpo dell'avversario$$ ,NULL ,NULL ),
    ( 15 , 'Uchi' ,'Choku tsuki',$$Pugno frontale sul posto$$ ,NULL ,NULL ),
    ( 16 , 'Uchi' ,'Enpi Uchi',$$Colpo di gomito$$ ,NULL ,NULL ),
    ( 17 , 'Geri' ,'Fumikiri',$$Calcio tagliente verso il basso$$ ,$$eseguito come uno YOKO GERI KEKOMI portato molto in basso: tibia, piede dell'avversario$$ ,NULL ),
    ( 18 , 'Geri' ,'Fumikomi',$$Calcio pressante (eseguito con una traiettoria dall'alto verso il basso, trasferendo tutto il peso del corpo sul piede che colpisce)$$ ,NULL ,NULL ),
    ( 19 , 'Uke' ,'Gedan barai',$$Parata verso il basso$$ ,NULL ,NULL ),
    ( 20 , 'Uke' ,'Gedan Kake uke',$$Parata bassa uncinante (eseguita facendo compiere all'avambraccio un ampio movimento dall'esterno verso l'interno; normalmente è usata per parare un MAEGERI)$$ ,NULL ,NULL ),
    ( 21 , NULL ,'Jodan Morote Haiwan Uke',$$Prima posizione di heian Nidan$$ ,NULL ,NULL ),
    ( 22 , 'Geri' ,'Gyaku mawashi geri',$$Calcio circolare contrario (è una variante del Mawashi geri, eseguito con traiettoria dall'interno verso l'esterno)$$ ,NULL ,NULL ),
    ( 23 , '_' ,'"e.c."',$$Pugno contrario (rispetto alla gamba avanzata)$$ ,NULL ,NULL ),
    ( 24 , 'Uke' ,'Haishu jkji uke',$$Parata con le mani a X (eseguita con le mani aperte ed i polsi uniti)$$ ,NULL ,NULL ),
    ( 25 , 'Uke' ,'Haishu uke',$$Parata con il dorso della mano$$ ,NULL ,NULL ),
    ( 26 , 'Uchi' ,'Haito Uchi',$$Colpo con la mano a coltello (eseguita colpendo con la parte interna del dorso della mano)$$ ,NULL ,NULL ),
    ( 27 , 'Uke' ,'Haiwan nagashi uke',$$Parata deviante con la parte esterna dell'avambraccio (eseguita spostando il braccio in avanti per intercettare l'attacco e deviandone la traiettoria)$$ ,NULL ,NULL ),
    ( 28 , 'Uchi' ,'Hasami tsuki',$$Pugni a forbice (eseguiti con un movimento degli arti in modo ampio e circolare, dall'esterno verso l'interno)$$ ,NULL ,NULL ),
    ( 29 , 'Geri' ,'Hiza geri',$$Ginocchiata$$ ,NULL ,NULL ),
    ( 30 , NULL ,'Hikite',$$Braccio carico pugno sulla cresta iliaca e gomito arretrato$$ ,NULL ,NULL ),
    ( 31 , 'Uke' ,'Juji uke',$$Parata a due mani ad X (effettuata con pugni chiusi e polsi uniti)$$ ,NULL ,NULL ),
    ( 32 , 'Uchi' ,'Kagi tsuki',$$Pugno a uncino (eseguito formando con il braccio un angolo di 90°)$$ ,NULL ,NULL ),
    ( 33 , 'Geri' ,'Kakato geri',$$Calcio con il tallone (eseguita facendo scendere il tallone dall'alto, dopo avere caricato il calcio lanciando la gamba verso l'alto)$$ ,NULL ,NULL ),
    ( 34 , 'Uke' ,'Kakiwake uke',$$Parata a due mani a cuneo rovesciato$$ ,NULL ,NULL ),
    ( 35 , 'Uke' ,'Kakuto uke',$$Parata con il polso a testa di gru$$ ,NULL ,NULL ),
    ( 36 , 'Uke' ,'Keito uke',$$Parata con la mano a testa di gallina$$ ,NULL ,NULL ),
    ( 37 , 'Geri' ,'Kizami Geri',$$$$ ,NULL ,NULL ),
    ( 38 , 'Uchi' ,'Kizami tsuki',$$Pugno anteriore (eseguito lanciando il pugno, corrispondente alla gamba avanzata, verso il bersaglio; il piede potrà rimanere fermo o essere spostato in avanti)$$ ,NULL ,NULL ),
    ( 39 , 'Uchi' ,'Mae Empi ',$$$$ ,NULL ,NULL ),
    ( 40 , 'Uchi' ,'Mae Enpi Uchi',$$Colpo di gomito frontale (eseguita sul piano orizzontale)$$ ,NULL ,NULL ),
    ( 41 , 'Geri' ,'Mae geri',$$Calcio frontale$$ ,NULL ,NULL ),
    ( 42 , 'Geri' ,'Mae tobi geri',$$Calcio volante frontale$$ ,NULL ,NULL ),
    ( 43 , 'Uchi' ,'Mawashi Enpi Uchi',$$Colpo di gomito circolare$$ ,NULL ,NULL ),
    ( 44 , 'Geri' ,'Mawashi geri',$$Calcio circolare$$ ,NULL ,NULL ),
    ( 45 , 'Uchi' ,'Mawashi tsuki',$$Pugno circolare$$ ,NULL ,NULL ),
    ( 46 , 'Geri' ,'Mikatsuki geri',$$Calcio a luna crescente (eseguito con una traiettoria circolare crescente dal suolo sino al bersaglio)$$ ,NULL ,NULL ),
    ( 47 , 'Uchi' ,'Morote tsuki',$$Colpo portato simultaneamente con due pugni$$ ,NULL ,NULL ),
    ( 48 , 'Uke' ,'Morote uke',$$Parata a due mani rinforzata$$ ,NULL ,NULL ),
    ( 49 , 'Geri' ,'Nidan geri',$$Calcio volante doppio (eseguito lanciando due MAE GERI in successione alternata mentre si è in elevazione; il primo colpisce al livello Chudan, il secondo, con l'altra gamba, a livello Jodan)$$ ,NULL ,NULL ),
    ( 50 , 'Uchi' ,'Nihon Nukite',$$$$ ,NULL ,NULL ),
    ( 51 , 'Uchi' ,'Oi tsuki',$$Pugno lungo$$ ,NULL ,NULL ),
    ( 52 , 'Uchi' ,'Otoshi Enpi Uchi',$$Colpo di gomito dall'alto verso il basso$$ ,NULL ,NULL ),
    ( 53 , 'Uke' ,'Otoshi uke',$$Parata discendente (eseguita facendo scendere l'avambraccio perpendicolarmente sull'avambraccio dell'avversario)$$ ,NULL ,NULL ),
    ( 54 , 'Geri' ,'Ren geri',$$Calcio alternato (eseguito lanciando due MAE GERI in successione alternata)$$ ,NULL ,NULL ),
    ( 55 , 'Uchi' ,'Sanbon tsuki',$$Combinazione di tre pugni (generalmente il primo è Jodan, gli altri due Chudan)$$ ,NULL ,NULL ),
    ( 56 , 'Uke' ,'Seirykto uke',$$Parata con la mano a spada cinese$$ ,NULL ,NULL ),
    ( 57 , 'Uchi' ,'Shuto Uchi',$$Colpo con la mano a coltello (eseguita colpendo con la parte esterna del dorso della mano)$$ ,NULL ,NULL ),
    ( 58 , 'Uke' ,'Shuto uke',$$Parata con il taglio della mano$$ ,NULL ,NULL ),
    ( 59 , 'Uke' ,'Sokumen awase uke',$$Parata laterale a due mani (eseguita utilizzando il palmo della mano che è rafforzata dal dorso dell'altra)$$ ,NULL ,NULL ),
    ( 60 , 'Uke' ,'Sokumen Haito Uke',$$$$ ,NULL ,NULL ),
    ( 61 , 'Uke' ,'Sokutei mawashi uke',$$Parata circolare con la pianta del piede$$ ,NULL ,NULL ),
    ( 62 , 'Uke' ,'Sokutei osae uke',$$Parata pressante con la pianta del piede (eseguita per fermare con molto anticipo un calcio che è ancora nella fase di caricamento)$$ ,NULL ,NULL ),
    ( 63 , 'Uke' ,'Sokuto osae uke',$$Parata pressante con il taglio del piede$$ ,NULL ,NULL ),
    ( 64 , 'Uke' ,'Soto Ude uke',$$Parata media eseguita con la parte esterna dell'avambraccio$$ ,NULL ,NULL ),
    ( 65 , 'Uchi' ,'Tate Enpi Uchi',$$Colpo di gomito frontale portato dal basso verso l'alto$$ ,NULL ,NULL ),
    ( 66 , 'Uke' ,'Tate Shuto uke',$$Parata con il taglio della mano verticale$$ ,NULL ,NULL ),
    ( 67 , 'Uke' ,'Te Nagashi uke',$$Parata deviante con la mano (eseguita intercettando il braccio dell'attaccante e deviandone la traiettoria con il palmo della propria mano).$$ ,NULL ,NULL ),
    ( 68 , 'Uke' ,'Te osae uke',$$Parata con la mano pressante (eseguita portando la propria mano ad intercettare l'avambraccio dell'attaccante, abbassandolo e tirandolo all'indietro, provocando lo sbilanciamento in avanti dell'avversario).$$ ,NULL ,NULL ),
    ( 69 , 'Uke' ,'Teisho awase uke',$$Parata con le basi dei palmi delle due mani (eseguita tenendo a contatto i polsi)$$ ,NULL ,NULL ),
    ( 70 , 'Uchi' ,'Teisho Uchi',$$Colpo con la base del palmo della mano$$ ,NULL ,NULL ),
    ( 71 , 'Uke' ,'Teisho uke',$$Parata con la base del palmo della mano$$ ,NULL ,NULL ),
    ( 72 , 'Uchi' ,'Tettsui Uchi',$$Colpo col pugno a martello$$ ,NULL ,NULL ),
    ( 73 , 'Uke' ,'Uchi Ude uke',$$Parata media eseguita con la parte interna dell'avambraccio$$ ,NULL ,NULL ),
    ( 74 , 'Geri' ,'Ura mawashi geri',$$Calcio circolare rovesciato$$ ,NULL ,NULL ),
    ( 75 , 'Uchi' ,'Ura tsuki',$$Pugno rovesciato (eseguito colpendo dal basso verso l'alto e arrivando al bersaglio con il palmo verso l'alto)$$ ,NULL ,NULL ),
    ( 76 , 'Uchi' ,'Uraken Uchi',$$Colpo col dorso del pugno$$ ,NULL ,NULL ),
    ( 77 , 'Uchi' ,'Ushiro Enpi Uchi',$$Colpo di gomito all'indietro$$ ,NULL ,NULL ),
    ( 78 , 'Geri' ,'Ushiro geri',$$Calcio all'indietro$$ ,NULL ,NULL ),
    ( 79 , 'Geri' ,'Ushiro mawashi geri',$$Calcio all'indietro circolare$$ ,NULL ,NULL ),
    ( 80 , 'Uchi' ,'Yama tsuki',$$Pugni a U larga$$ ,NULL ,NULL ),
    ( 81 , 'Uchi' ,'Yoko Enpi Uchi',$$Colpo di gomito laterale$$ ,NULL ,NULL ),
    ( 82 , 'Geri' ,'Yoko geri Keage',$$Calcio laterale frustato$$ ,NULL ,NULL ),
    ( 83 , 'Geri' ,'Yoko geri Kekomi',$$Calcio laterale spinto$$ ,NULL ,NULL ),
    ( 84 , 'Geri' ,'Yoko Tobi geri',$$Calcio volante laterale$$ ,NULL ,NULL ),
    ( 85 , 'Uke' ,'Age Shuto Uke',$$Parata a taglio verso l'alto (movimento che si fa con la mano opposta quando si esegue Age uke da studio)$$ ,NULL ,NULL ),
    ( 86 , 'Uchi' ,'Nukite',$$Colpo con la punta delle dita con la mano distesa$$ ,NULL ,NULL ),
    ( 87 , 'Uke' ,'Empi Uke',$$Braccio forma un triangolo tra spalla gomito e cresta iliaca (parata del 3 kata)$$ ,NULL ,NULL ),
    ( 88 , NULL ,'Gedan Kekomi',$$$$ ,NULL ,NULL ),
    ( 90 , NULL ,'Mawatte',$$Cambio di direzione, 180° dal lato interno$$ ,NULL ,NULL ),
    ( -500 , '_' ,'Vedi note',$$$$ ,NULL ,NULL ),
    ( -200 , 'NA' ,'Shi Ho Soto Uke Gyakuzuki',$$Quattro direzioni$$ ,NULL ,NULL ),
    ( -201 , 'NA' ,'Shi Ho Gyakuzuki',$$$$ ,NULL ,NULL ),
    ( -202 , 'NA' ,'Shi Ho UchiUke Gyakuzuki',$$$$ ,NULL ,NULL ),
    ( -203 , 'NA' ,'Shi Ho Tate Empi Mae Empi',$$$$ ,NULL ,NULL ),
    ( -250 , 'NA' ,'Kime Waza',$$Controllo$$ ,NULL ,NULL )
;

INSERT INTO ski.stands(id_stand ,name ,description ,illustration_url ,notes ) VALUES
    ( 1 ,'Heiko dachi' ,$$Posizione naturale a gambe divaricate e piedi paralleli (YOI)$$ ,NULL ,NULL ),
    ( 2 ,'Musubi dachi' ,$$Posizione naturale con talloni uniti e punte divaricate a 90° (nel saluto)$$ ,NULL ,NULL ),
    ( 3 ,'Heisoku dachi' ,$$Posizione naturale con piedi e talloni uniti$$ ,NULL ,NULL ),
    ( 4 ,'Zenkutsu dachi' ,$$Posizione frontale$$ ,NULL ,NULL ),
    ( 5 ,'Kokutsu dachi' ,$$Posizione basata sulla gamba posteriore$$ ,NULL ,'Peso 30% gamba anteriore e 70% al posteriore' ),
    ( 6 ,'Kiba dachi' ,$$Posizione del cavaliere$$ ,NULL ,NULL ),
    ( 7 ,'Shiko dachi' ,$$Posizione quadrata$$ ,NULL ,NULL ),
    ( 8 ,'Hangetsu dachi' ,$$Posizione a Mezza luna$$ ,NULL ,NULL ),
    ( 9 ,'Sochin dachi' ,$$Posizione consolidata$$ ,NULL ,'Detta anche Fudo dachi' ),
    ( 10 ,'Neko ashi dachi' ,$$Posizione a gatto$$ ,NULL ,NULL ),
    ( 11 ,'Sanchin dachi' ,$$Posizione a clessidra$$ ,NULL ,NULL ),
    ( 12 ,'Hachinoji dachi' ,$$Posizione naturale a gambe divaricate e punte divaricate a 90°$$ ,NULL ,NULL ),
    ( 13 ,'Hachiji dachi' ,$$Posizione naturale a gambe divaricate$$ ,NULL ,NULL ),
    ( 14 ,'UchiHachiji dachi' ,$$Posizione a gambe divaricate e punte dei piedi all'interno$$ ,NULL ,NULL ),
    ( 15 ,'Teiji dachi' ,$$Posizione naturale con i piedi a forma di T$$ ,NULL ,NULL ),
    ( 16 ,'Renoji dachi' ,$$Posizione naturale con i piedi a forma di L$$ ,NULL ,NULL )
;

INSERT INTO ski.grades (id_grade,gtype,grade, color) VALUES 
    ( 1 , 'kyu' , 9 , 'bianco' ),
    ( 2 , 'kyu' , 8 , 'bianco' ),
    ( 3 , 'kyu' , 7 , 'bianco' ),
    ( 4 , 'kyu' , 6 , 'giallo' ),
    ( 5 , 'kyu' , 5 , 'verde' ),
    ( 6 , 'kyu' , 4 , 'blu' ),
    ( 7 , 'kyu' , 3 , 'marrone' ),
    ( 8 , 'kyu' , 2 , 'marrone' ),
    ( 9 , 'kyu' , 1 , 'marrone' ),
    ( 10 , 'dan' , 1 , 'nero' ),
    ( 11 , 'dan' , 2 , 'nero' ),
    ( 12 , 'dan' , 3 , 'nero' ),
    ( 13 , 'dan' , 4 , 'nero' ),
    ( 14 , 'dan' , 5 , 'nero' ),
    ( 15 , 'dan' , 6 , 'nero' ),
    ( 16 , 'dan' , 7 , 'nero' )
;

--da aggiornare
INSERT INTO ski.kihon_inventory(id_inventory ,grade_id ,number,resources,notes ) VALUES
    ( 1 ,1 ,1 , $${"chiave":"valore","secondachiave":"secondo valore"}$$::jsonb , $$nota$$ ),
    ( 2 ,1 ,2 , NULL , NULL ),
    ( 3 ,1 ,3 , NULL , NULL ),
    ( 4 ,1 ,4 , NULL , NULL ),
    ( 5 ,1 ,5 , NULL , NULL ),
    ( 6 ,1 ,6 , NULL , NULL ),
    ( 7 ,1 ,7 , NULL , NULL ),
    ( 8 ,1 ,8 , NULL , NULL ),
    ( 9 ,1 ,9 , NULL , NULL ),
    ( 11 ,2 ,1 , NULL , NULL ),
    ( 12 ,2 ,2 , NULL , NULL ),
    ( 13 ,2 ,3 , NULL , NULL ),
    ( 14 ,2 ,4 , NULL , NULL ),
    ( 15 ,2 ,5 , NULL , NULL ),
    ( 16 ,2 ,6 , NULL , NULL ),
    ( 17 ,2 ,7 , NULL , NULL ),
    ( 18 ,2 ,8 , NULL , NULL ),
    ( 19 ,2 ,9 , NULL , NULL ),
    ( 20 ,2 ,10 , NULL , NULL ),
    ( 21 ,3 ,1 , NULL , NULL ),
    ( 22 ,3 ,2 , NULL , NULL ),
    ( 23 ,3 ,3 , NULL , NULL ),
    ( 24 ,3 ,4 , NULL , NULL ),
    ( 25 ,3 ,5 , NULL , NULL ),
    ( 26 ,3 ,6 , NULL , NULL ),
    ( 27 ,3 ,7 , NULL , NULL ),
    ( 28 ,3 ,8 , NULL , NULL ),
    ( 29 ,3 ,9 , NULL , NULL ),
    ( 30 ,3 ,10 , NULL , NULL ),
    ( 31 ,4 ,1 , NULL , NULL ),
    ( 32 ,4 ,2 , NULL , NULL ),
    ( 33 ,4 ,3 , NULL , NULL ),
    ( 34 ,4 ,4 , NULL , NULL ),
    ( 35 ,4 ,5 , NULL , NULL ),
    ( 36 ,4 ,6 , NULL , NULL ),
    ( 37 ,4 ,7 , NULL , NULL ),
    ( 38 ,4 ,8 , NULL , NULL ),
    ( 39 ,4 ,9 , NULL , NULL ),
    ( 40 ,4 ,10 , NULL , NULL ),
    ( 41 ,5 ,1 , NULL , NULL ),
    ( 42 ,5 ,2 , NULL , NULL ),
    ( 43 ,5 ,3 , NULL , NULL ),
    ( 44 ,5 ,4 , NULL , NULL ),
    ( 45 ,5 ,5 , NULL , NULL ),
    ( 46 ,5 ,6 , NULL , NULL ),
    ( 47 ,5 ,7 , NULL , NULL ),
    ( 48 ,5 ,8 , NULL , NULL ),
    ( 49 ,5 ,9 , NULL , NULL ),
    ( 50 ,5 ,10 , NULL , NULL ),
    ( 51 ,6 ,1 , NULL , NULL ),
    ( 52 ,6 ,2 , NULL , NULL ),
    ( 53 ,6 ,3 , NULL , NULL ),
    ( 54 ,6 ,4 , NULL , NULL ),
    ( 55 ,6 ,5 , NULL , NULL ),
    ( 56 ,6 ,6 , NULL , NULL ),
    ( 57 ,6 ,7 , NULL , NULL ),
    ( 58 ,6 ,8 , NULL , NULL ),
    ( 59 ,6 ,9 , NULL , NULL ),
    ( 60 ,6 ,10 , NULL , NULL ),
    ( 61 ,7 ,1 , NULL , NULL ),
    ( 62 ,7 ,2 , NULL , NULL ),
    ( 63 ,7 ,3 , NULL , NULL ),
    ( 64 ,7 ,4 , NULL , NULL ),
    ( 65 ,7 ,5 , NULL , NULL ),
    ( 66 ,7 ,6 , NULL , NULL ),
    ( 67 ,7 ,7 , NULL , NULL ),
    ( 68 ,7 ,8 , NULL , NULL ),
    ( 69 ,7 ,9 , NULL , NULL ),
    ( 70 ,7 ,10 , NULL , NULL ),
    ( 71 ,8 ,1 , NULL , NULL ),
    ( 72 ,8 ,2 , NULL , NULL ),
    ( 73 ,8 ,3 , NULL , NULL ),
    ( 74 ,8 ,4 , NULL , NULL ),
    ( 75 ,8 ,5 , NULL , NULL ),
    ( 76 ,8 ,6 , NULL , NULL ),
    ( 77 ,8 ,7 , NULL , NULL ),
    ( 78 ,8 ,8 , NULL , NULL ),
    ( 79 ,8 ,9 , NULL , NULL ),
    ( 80 ,8 ,10 , NULL , NULL ),
    ( 81 ,9 ,1 , NULL , NULL ),
    ( 82 ,9 ,2 , NULL , NULL ),
    ( 83 ,9 ,3 , NULL , NULL ),
    ( 84 ,9 ,4 , NULL , NULL ),
    ( 85 ,9 ,5 , NULL , NULL ),
    ( 86 ,9 ,6 , NULL , NULL ),
    ( 87 ,9 ,7 , NULL , NULL ),
    ( 88 ,9 ,8 , NULL , NULL ),
    ( 89 ,9 ,9 , NULL , NULL ),
    ( 91 ,10 ,1 , NULL , NULL ),
    ( 92 ,10 ,2 , NULL , NULL ),
    ( 93 ,10 ,3 , NULL , NULL ),
    ( 94 ,10 ,4 , NULL , NULL ),
    ( 95 ,10 ,5 , NULL , NULL ),
    ( 96 ,10 ,6 , NULL , NULL ),
    ( 97 ,10 ,7 , NULL , NULL ),
    ( 98 ,10 ,8 , NULL , NULL ),
    ( 99 ,10 ,9 , NULL , NULL ),
    ( 100 ,10 ,10 , NULL , NULL ),
    ( 101 ,11 ,1 , NULL , NULL ),
    ( 102 ,11 ,2 , NULL , NULL ),
    ( 103 ,11 ,3 , NULL , NULL ),
    ( 104 ,11 ,4 , NULL , NULL ),
    ( 105 ,11 ,5 , NULL , NULL ),
    ( 106 ,11 ,6 , NULL , NULL ),
    ( 107 ,11 ,7 , NULL , NULL ),
    ( 108 ,11 ,8 , NULL , NULL ),
    ( 109 ,11 ,9 , NULL , NULL ),
    ( 110 ,11 ,10 , NULL , NULL ),
    ( 111 ,12 ,1 , NULL , NULL ),
    ( 112 ,12 ,2 , NULL , NULL ),
    ( 113 ,12 ,3 , NULL , NULL ),
    ( 114 ,12 ,4 , NULL , NULL ),
    ( 115 ,12 ,5 , NULL , NULL ),
    ( 116 ,12 ,6 , NULL , NULL ),
    ( 117 ,12 ,7 , NULL , NULL ),
    ( 118 ,12 ,8 , NULL , NULL ),
    ( 119 ,12 ,9 , NULL , NULL ),
    ( 120 ,12 ,10 , NULL , NULL )
;

 
INSERT INTO ski.kihon_sequences(
    id_sequence, 
    inventory_id , 
    seq_num,
    stand_id,
    technic_id,
    hips,
    gyaku,
    target_hgt,
    resources,
    notes,
    resource_url
) VALUES 
    ( 1 ,1 ,0,4 , 1 ,NULL , 'false' ,'Jodan' , $${"chiave":"valore","secondachiave":"secondo valore"}$$::jsonb , NULL , NULL ),
    ( 2 ,1 ,1,4 , 15 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 3 ,2 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 4 ,2 ,1,4 , 11 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 5 ,3 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 6 ,3 ,1,4 , 64 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 7 ,4 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 8 ,4 ,1,4 , 19 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 9 ,5 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 10 ,5 ,1,4 , 51 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 11 ,6 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 12 ,6 ,1,4 , 11 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 13 ,7 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 14 ,7 ,1,4 , 64 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 15 ,8 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 16 ,8 ,1,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 17 ,9 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 18 ,9 ,1,4 , 90 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 19 ,9 ,2,4 , 19 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 21 ,11 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 22 ,11 ,1,4 , 51 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 23 ,12 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 24 ,12 ,1,4 , 11 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 25 ,13 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 26 ,13 ,1,4 , 64 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 27 ,14 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 28 ,14 ,1,4 , 19 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 29 ,15 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 30 ,15 ,1,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 31 ,16 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 32 ,16 ,1,4 , 11 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 33 ,16 ,2,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 34 ,17 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 35 ,17 ,1,4 , 64 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 36 ,17 ,2,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 37 ,18 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 38 ,18 ,1,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 39 ,19 ,0,4 , 1 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 40 ,19 ,1,4 , 58 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 41 ,20 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 42 ,20 ,1,4 , 19 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 43 ,20 ,2,16 , 72 ,NULL , 'false' ,NULL , NULL , $$Tatemawasci Tettsui Uchi$$ , NULL ),
    ( 50 ,21 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 51 ,21 ,1,4 , 51 ,NULL , 'false' ,'Jodan' , NULL , NULL , NULL ),
    ( 52 ,22 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 53 ,22 ,1,4 , 11 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 54 ,22 ,2,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 55 ,23 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 56 ,23 ,1,4 , 64 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 57 ,23 ,2,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 58 ,24 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 59 ,24 ,1,4 , 19 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 60 ,24 ,2,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 61 ,25 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 62 ,25 ,1,4 , 73 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 63 ,26 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 64 ,26 ,1,4 , 58 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 65 ,27 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 66 ,27 ,1,4 , 41 ,NULL , 'false' ,'Jodan' , NULL , NULL , NULL ),
    ( 67 ,28 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 68 ,28 ,1,6 , 82 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 69 ,29 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 70 ,29 ,1,6 , 83 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 71 ,30 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 72 ,30 ,1,4 , 73 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 73 ,30 ,2,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 74 ,30 ,3,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 80 ,31 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 81 ,31 ,1,4 , 51 ,NULL , 'false' ,'Jodan' , NULL , NULL , NULL ),
    ( 82 ,31 ,2,4 , 14 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 83 ,32 ,0,4 , 1 ,NULL , 'true' ,'Chudan' , NULL , NULL , NULL ),
    ( 84 ,32 ,1,4 , 11 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 85 ,32 ,2,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 86 ,32 ,3,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 87 ,33 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 88 ,33 ,1,4 , 64 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 89 ,33 ,2,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 90 ,33 ,3,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 91 ,34 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 92 ,34 ,1,4 , 73 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 93 ,34 ,2,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 94 ,34 ,3,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 95 ,35 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 96 ,35 ,1,4 , 19 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 97 ,35 ,2,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 98 ,35 ,3,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 99 ,36 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 100 ,36 ,1,4 , 57 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 101 ,37 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 102 ,37 ,1,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 103 ,37 ,2,4 , 51 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 104 ,38 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 105 ,38 ,1,6 , 82 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 106 ,39 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 107 ,39 ,1,6 , 83 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 108 ,40 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 109 ,40 ,1,3 , 18 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 110 ,40 ,2,3 , 87 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 111 ,40 ,3,6 , 76 ,NULL , 'false' ,'Jodan' , NULL , NULL , NULL ),
    ( 120 ,41 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 121 ,41 ,1,4 , 51 ,NULL , 'false' ,'Jodan' , NULL , NULL , NULL ),
    ( 122 ,41 ,2,4 , 14 ,NULL , 'true' ,'Chudan' , NULL , NULL , NULL ),
    ( 123 ,42 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 124 ,42 ,1,4 , 11 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 125 ,42 ,2,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 126 ,42 ,3,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 127 ,43 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 128 ,43 ,1,4 , 64 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 129 ,43 ,2,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 130 ,43 ,3,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 131 ,44 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 132 ,44 ,1,4 , 73 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 133 ,44 ,2,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 134 ,44 ,3,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 135 ,45 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 136 ,45 ,1,4 , 19 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 137 ,45 ,2,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 138 ,45 ,3,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 139 ,46 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 140 ,46 ,1,5 , 48 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 141 ,46 ,2,4 , 14 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 151 ,47 ,0,4 , 1 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 152 ,47 ,1,4 , 58 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 153 ,47 ,2,4 , 86 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 154 ,48 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 155 ,48 ,1,4 , 82 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 156 ,49 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 157 ,49 ,1,4 , 83 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 158 ,50 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 159 ,50 ,1,4 , 54 ,NULL , 'false' ,NULL , NULL , $$Chudan,jodan$$ , NULL ),
    ( 170 ,51 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 171 ,51 ,1,4 , 55 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 172 ,52 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 173 ,52 ,1,4 , 73 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 174 ,52 ,2,4 , 38 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 175 ,52 ,3,4 , 51 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 176 ,53 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 177 ,53 ,1,4 , 11 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 178 ,53 ,2,4 , 81 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 179 ,53 ,3,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 180 ,54 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 181 ,54 ,1,4 , 64 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 182 ,54 ,2,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 183 ,54 ,3,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 184 ,55 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 185 ,55 ,1,4 , 14 ,NULL , 'true' ,'Jodan' , NULL , NULL , NULL ),
    ( 186 ,55 ,2,4 , 14 ,NULL , 'true' ,'Chudan' , NULL , NULL , NULL ),
    ( 187 ,56 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 188 ,56 ,1,4 , 19 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 189 ,56 ,2,4 , 39 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 190 ,57 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 191 ,57 ,1,4 , 58 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 192 ,57 ,2,4 , 37 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 193 ,57 ,3,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 194 ,58 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 195 ,58 ,1,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 196 ,58 ,2,4 , 83 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 197 ,59 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 198 ,59 ,1,4 , 44 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 199 ,60 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 200 ,60 ,1,4 , 31 ,NULL , 'false' ,'Gedan' , NULL , NULL , NULL ),
    ( 201 ,60 ,2,4 , 76 ,NULL , 'false' ,'Jodan' , NULL , NULL , NULL ),
    ( 202 ,60 ,3,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 203 ,61 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 204 ,61 ,1,4 , 55 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 205 ,61 ,2,4 , 51 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 206 ,62 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 207 ,62 ,1,4 , 11 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 208 ,62 ,2,4 , 19 ,NULL , 'false' ,NULL , NULL , $$Stessa mano$$ , NULL ),
    ( 209 ,62 ,3,4 , 51 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 210 ,63 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 211 ,63 ,1,4 , 64 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 212 ,63 ,2,4 , 76 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 213 ,63 ,3,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 214 ,64 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 215 ,64 ,1,4 , 73 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 216 ,64 ,2,4 , 38 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 217 ,64 ,3,4 , 64 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 218 ,64 ,4,4 , 11 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 219 ,64 ,5,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 220 ,65 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 221 ,65 ,1,4 , 58 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 222 ,65 ,2,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 223 ,65 ,3,4 , 19 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 224 ,65 ,4,4 , 15 ,NULL , 'false' ,'Jodan' , NULL , NULL , NULL ),
    ( 225 ,66 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 226 ,66 ,1,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 227 ,66 ,2,4 , 44 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 228 ,67 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 229 ,67 ,1,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 230 ,67 ,2,4 , 83 ,NULL , 'false' ,NULL , NULL , $$Stessa gamba$$ , NULL ),
    ( 231 ,68 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 232 ,68 ,1,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 233 ,68 ,2,4 , 44 ,NULL , 'false' ,NULL , NULL , $$Stessa gamba$$ , NULL ),
    ( 234 ,69 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 235 ,69 ,1,4 , 19 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 236 ,69 ,2,4 , 11 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 237 ,69 ,3,4 , 15 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 238 ,70 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 239 ,70 ,1,4 , -201 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 250 ,71 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 251 ,71 ,1,4 , 55 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 252 ,71 ,2,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 253 ,71 ,3,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 254 ,72 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 255 ,72 ,1,4 , 73 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 256 ,72 ,2,4 , 73 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 257 ,72 ,3,4 , 44 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 258 ,72 ,4,4 , 76 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 259 ,72 ,5,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 260 ,73 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 261 ,73 ,1,4 , 11 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 262 ,73 ,2,4 , 27 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 263 ,73 ,3,4 , 40 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 268 ,74 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 269 ,74 ,1,4 , 64 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 270 ,74 ,2,4 , 37 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 271 ,74 ,3,4 , 51 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 272 ,75 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 273 ,75 ,1,4 , 51 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 274 ,75 ,2,5 , 66 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 275 ,75 ,3,4 , 46 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 276 ,76 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 277 ,76 ,1,4 , 78 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 278 ,77 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 279 ,77 ,1,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 280 ,77 ,2,4 , 83 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 281 ,77 ,3,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 282 ,78 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 283 ,78 ,1,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 284 ,78 ,2,4 , 44 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 285 ,78 ,3,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 286 ,79 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 287 ,79 ,1,4 , 44 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 288 ,79 ,2,4 , 44 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 289 ,79 ,3,4 , 14 ,NULL , 'true' ,'Jodan' , NULL , NULL , NULL ),
    ( 290 ,80 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 291 ,80 ,1,4 , -202 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 300 ,81 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 301 ,81 ,1,4 , 51 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 302 ,81 ,2,4 , 58 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 303 ,81 ,3,4 , 37 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 304 ,81 ,4,4 , 11 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 305 ,81 ,5,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 306 ,82 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 307 ,82 ,1,4 , 38 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 308 ,82 ,2,5 , 64 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 309 ,82 ,3,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 310 ,82 ,4,4 , 44 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 311 ,83 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 312 ,83 ,1,4 , 76 ,NULL , 'false' ,'Jodan' , NULL , NULL , NULL ),
    ( 313 ,83 ,2,4 , 73 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 314 ,83 ,3,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 315 ,84 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 316 ,84 ,1,4 , 11 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 317 ,84 ,2,4 , 26 ,NULL , 'true' ,'Jodan' , NULL , NULL , NULL ),
    ( 318 ,84 ,3,4 , 83 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 319 ,84 ,4,4 , 78 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 320 ,84 ,5,4 , 14 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 321 ,85 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 322 ,85 ,1,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 323 ,85 ,2,4 , 76 ,NULL , 'true' ,NULL , NULL , NULL , NULL ),
    ( 324 ,85 ,3,4 , 19 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 325 ,85 ,4,4 , 86 ,NULL , 'true' ,'Chudan' , NULL , NULL , NULL ),
    ( 326 ,86 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 327 ,86 ,1,4 , 41 ,NULL , 'false' ,'Jodan' , NULL , NULL , NULL ),
    ( 328 ,86 ,2,4 , -500 ,NULL , 'false' ,NULL , NULL , $$Dice gedan kekomi$$ , NULL ),
    ( 329 ,86 ,3,4 , 73 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 330 ,86 ,4,4 , 44 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 331 ,86 ,5,4 , 58 ,NULL , 'false' ,NULL , NULL , $$Ruotare 180 °$$ , NULL ),
    ( 332 ,87 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 333 ,87 ,1,4 , 41 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 334 ,87 ,2,4 , 83 ,NULL , 'false' ,NULL , NULL , $$Stessa gamba$$ , NULL ),
    ( 335 ,87 ,3,4 , 78 ,NULL , 'false' ,NULL , NULL , $$Stessa gamba$$ , NULL ),
    ( 336 ,88 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 337 ,88 ,1,4 , -203 ,NULL , 'false' ,NULL , NULL , $$Parata esterna$$ , NULL ),
    ( 340 ,89 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 341 ,89 ,1,4 , -250 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 456 ,91 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 457 ,91 ,1,4 , 70 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 458 ,91 ,2,4 , 11 ,NULL , 'true' ,'Chudan' , NULL , NULL , NULL ),
    ( 459 ,91 ,3,4 , 26 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 460 ,91 ,4,4 , 40 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 466 ,92 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 467 ,92 ,1,4 , 36 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 468 ,92 ,2,9 , 52 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 469 ,92 ,3,4 , 64 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 470 ,92 ,4,4 , 76 ,NULL , 'true' ,'Jodan' , NULL , NULL , NULL ),
    ( 476 ,93 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 477 ,93 ,1,4 , 34 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 478 ,93 ,2,4 , 80 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 479 ,93 ,3,4 , 29 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 480 ,93 ,4,4 , 65 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 486 ,94 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 487 ,94 ,1,4 , 2 ,NULL , 'false' ,'Chudan' , NULL , $$Il braccio del lato che è davanti deve essere proteso con il pugno formando una leggera curvatura.$$ , NULL ),
    ( 488 ,94 ,2,9 , 15 ,NULL , 'false' ,'Chudan' , NULL , $$Il braccio che era davanti resta in posizione avanzata formando una protezione, mantre viene sferrato il pugno.$$ , NULL ),
    ( 496 ,95 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 497 ,95 ,1,4 , 35 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 498 ,95 ,2,4 , 14 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 499 ,95 ,3,4 , 18 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 500 ,95 ,4,4 , 50 ,NULL , 'false' ,'Jodan' , NULL , NULL , NULL ),
    ( 506 ,96 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 507 ,96 ,1,4 , 73 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 508 ,96 ,2,4 , 78 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 509 ,96 ,3,6 , 50 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 510 ,96 ,4,4 , 32 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 516 ,97 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 517 ,97 ,1,4 , 83 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 518 ,97 ,2,4 , 41 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 526 ,98 ,0,4 , 1 ,NULL , 'false' ,NULL , NULL , NULL , NULL ),
    ( 527 ,98 ,1,4 , 37 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 528 ,98 ,2,4 , 38 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 529 ,98 ,3,4 , 41 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 530 ,98 ,4,4 , 14 ,NULL , 'true' ,'Chudan' , NULL , NULL , NULL ),
    ( 537 ,99 ,1,4 , -200 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL ),
    ( 541 ,100 ,1,4 , -250 ,NULL , 'false' ,'Chudan' , NULL , NULL , NULL )
;

 
INSERT INTO ski.kihon_tx(
    id_tx ,
    from_sequence ,
    to_sequence ,
    movement , 
    resources,
    notes ,
    tempo,
    resource_url 
) VALUES
    ( 1 , 1 , 2, 'Still' , $${"chiave":"valore","secondachiave":"secondo valore"}$$::jsonb , NULL , 'Normal' , NULL ),
    ( 4 , 3 , 4, 'Still' , NULL , NULL , 'Normal' , NULL ),
    ( 7 , 5 , 6, 'Still' , NULL , NULL , 'Normal' , NULL ),
    ( 10 , 7 , 8, 'Still' , NULL , NULL , 'Normal' , NULL ),
    ( 13 , 9 , 10, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 16 , 11 , 12, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 19 , 13 , 14, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 22 , 15 , 16, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 25 , 17 , 18, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 26 , 18 , 19, 'Still' , NULL , NULL , NULL , NULL ),
    ( 29 , 21 , 22, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 32 , 23 , 24, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 35 , 25 , 26, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 38 , 27 , 28, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 41 , 29 , 30, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 44 , 31 , 32, 'Still' , NULL , NULL , NULL , NULL ),
    ( 45 , 32 , 33, 'Still' , NULL , NULL , NULL , NULL ),
    ( 48 , 34 , 35, 'Still' , NULL , NULL , NULL , NULL ),
    ( 49 , 35 , 36, 'Still' , NULL , NULL , NULL , NULL ),
    ( 52 , 37 , 38, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 55 , 39 , 40, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 58 , 41 , 42, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 59 , 42 , 43, 'Still' , NULL , NULL , NULL , NULL ),
    ( 62 , 50 , 51, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 65 , 52 , 53, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 66 , 53 , 54, 'Still' , NULL , NULL , NULL , NULL ),
    ( 69 , 55 , 56, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 70 , 56 , 57, 'Still' , NULL , NULL , NULL , NULL ),
    ( 73 , 58 , 59, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 74 , 59 , 60, 'Still' , NULL , NULL , NULL , NULL ),
    ( 77 , 61 , 62, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 80 , 63 , 64, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 83 , 65 , 66, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 86 , 67 , 68, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 89 , 69 , 70, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 92 , 71 , 72, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 93 , 72 , 73, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 94 , 73 , 74, 'Still' , NULL , NULL , NULL , NULL ),
    ( 97 , 80 , 81, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 98 , 81 , 82, 'Still' , NULL , NULL , NULL , NULL ),
    ( 101 , 83 , 84, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 102 , 84 , 85, 'Still' , NULL , NULL , NULL , NULL ),
    ( 103 , 85 , 86, 'Still' , NULL , NULL , NULL , NULL ),
    ( 106 , 87 , 88, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 107 , 88 , 89, 'Still' , NULL , NULL , NULL , NULL ),
    ( 108 , 89 , 90, 'Still' , NULL , NULL , NULL , NULL ),
    ( 111 , 91 , 92, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 112 , 92 , 93, 'Still' , NULL , NULL , NULL , NULL ),
    ( 113 , 93 , 94, 'Still' , NULL , NULL , NULL , NULL ),
    ( 116 , 95 , 96, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 117 , 96 , 97, 'Still' , NULL , NULL , NULL , NULL ),
    ( 118 , 97 , 98, 'Still' , NULL , NULL , NULL , NULL ),
    ( 121 , 99 , 100, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 124 , 101 , 102, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 125 , 102 , 103, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 128 , 104 , 105, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 131 , 106 , 107, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 134 , 108 , 109, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 135 , 109 , 110, 'Still' , NULL , NULL , NULL , NULL ),
    ( 136 , 110 , 111, 'Still' , NULL , NULL , NULL , NULL ),
    ( 139 , 120 , 121, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 142 , 121 , 122, 'Still' , NULL , NULL , NULL , NULL ),
    ( 145 , 123 , 124, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 148 , 124 , 125, 'Still' , NULL , NULL , NULL , NULL ),
    ( 151 , 125 , 126, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 154 , 127 , 128, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 157 , 128 , 129, 'Still' , NULL , NULL , NULL , NULL ),
    ( 160 , 129 , 130, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 163 , 131 , 132, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 166 , 132 , 133, 'Still' , NULL , NULL , NULL , NULL ),
    ( 169 , 133 , 134, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 172 , 135 , 136, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 175 , 136 , 137, 'Still' , NULL , NULL , NULL , NULL ),
    ( 176 , 137 , 138, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 179 , 139 , 140, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 182 , 140 , 141, 'Still' , NULL , NULL , NULL , NULL ),
    ( 185 , 151 , 152, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 188 , 152 , 153, 'Still' , NULL , NULL , NULL , NULL ),
    ( 191 , 154 , 155, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 194 , 156 , 157, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 197 , 158 , 159, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 200 , 170 , 171, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 203 , 172 , 173, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 206 , 173 , 174, 'Still' , NULL , NULL , NULL , NULL ),
    ( 209 , 174 , 175, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 212 , 176 , 177, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 215 , 177 , 178, 'Still' , NULL , NULL , NULL , NULL ),
    ( 218 , 178 , 179, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 221 , 180 , 181, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 224 , 181 , 182, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 227 , 182 , 183, 'Still' , NULL , NULL , NULL , NULL ),
    ( 230 , 184 , 185, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 233 , 185 , 186, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 236 , 187 , 188, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 239 , 188 , 189, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 242 , 190 , 191, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 245 , 191 , 192, 'Still' , NULL , NULL , NULL , NULL ),
    ( 248 , 192 , 193, 'Still' , NULL , NULL , NULL , NULL ),
    ( 251 , 194 , 195, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 254 , 195 , 196, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 257 , 197 , 198, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 260 , 199 , 200, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 263 , 200 , 201, 'Still' , NULL , NULL , NULL , NULL ),
    ( 266 , 201 , 202, 'Still' , NULL , NULL , NULL , NULL ),
    ( 269 , 203 , 204, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 272 , 204 , 205, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 275 , 206 , 207, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 278 , 207 , 208, 'Still' , NULL , NULL , NULL , NULL ),
    ( 281 , 208 , 209, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 284 , 210 , 211, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 287 , 211 , 212, 'Still' , NULL , NULL , NULL , NULL ),
    ( 290 , 212 , 213, 'Still' , NULL , NULL , NULL , NULL ),
    ( 293 , 214 , 215, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 296 , 215 , 216, 'Still' , NULL , NULL , NULL , NULL ),
    ( 299 , 216 , 217, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 302 , 217 , 218, 'Still' , NULL , NULL , NULL , NULL ),
    ( 305 , 218 , 219, 'Still' , NULL , NULL , NULL , NULL ),
    ( 308 , 220 , 221, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 311 , 221 , 222, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 314 , 222 , 223, 'Still' , NULL , NULL , NULL , NULL ),
    ( 317 , 223 , 224, 'Still' , NULL , NULL , NULL , NULL ),
    ( 320 , 225 , 226, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 323 , 226 , 227, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 326 , 228 , 229, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 329 , 229 , 230, 'Still' , NULL , NULL , NULL , NULL ),
    ( 332 , 231 , 232, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 335 , 232 , 233, 'Still' , NULL , NULL , NULL , NULL ),
    ( 338 , 234 , 235, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 341 , 235 , 236, 'Still' , NULL , NULL , NULL , NULL ),
    ( 344 , 236 , 237, 'Still' , NULL , NULL , NULL , NULL ),
    ( 347 , 238 , 239, 'Still' , NULL , NULL , NULL , NULL ),
    ( 350 , 250 , 251, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 353 , 251 , 252, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 356 , 252 , 253, 'Still' , NULL , NULL , NULL , NULL ),
    ( 359 , 254 , 255, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 362 , 255 , 256, 'Still' , NULL , NULL , NULL , NULL ),
    ( 365 , 256 , 257, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 368 , 257 , 258, 'Still' , NULL , NULL , NULL , NULL ),
    ( 371 , 258 , 259, 'Still' , NULL , NULL , NULL , NULL ),
    ( 374 , 260 , 261, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 377 , 261 , 262, 'Still' , NULL , NULL , NULL , NULL ),
    ( 378 , 262 , 263, 'Still' , NULL , NULL , NULL , NULL ),
    ( 381 , 268 , 269, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 384 , 269 , 270, 'Still' , NULL , NULL , NULL , NULL ),
    ( 387 , 270 , 271, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 390 , 272 , 273, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 393 , 273 , 274, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 396 , 274 , 275, 'Still' , NULL , NULL , NULL , NULL ),
    ( 399 , 276 , 277, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 402 , 278 , 279, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 405 , 279 , 280, 'Still' , NULL , NULL , NULL , NULL ),
    ( 408 , 280 , 281, 'Still' , NULL , NULL , NULL , NULL ),
    ( 411 , 282 , 283, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 414 , 283 , 284, 'Still' , NULL , NULL , NULL , NULL ),
    ( 417 , 284 , 285, 'Still' , NULL , NULL , NULL , NULL ),
    ( 420 , 286 , 287, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 423 , 287 , 288, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 426 , 288 , 289, 'Still' , NULL , NULL , NULL , NULL ),
    ( 429 , 290 , 291, 'Still' , NULL , NULL , NULL , NULL ),
    ( 432 , 300 , 301, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 435 , 301 , 302, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 438 , 302 , 303, 'Still' , NULL , NULL , NULL , NULL ),
    ( 441 , 303 , 304, 'Still' , NULL , NULL , NULL , NULL ),
    ( 444 , 304 , 305, 'Still' , NULL , NULL , NULL , NULL ),
    ( 447 , 306 , 307, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 450 , 307 , 308, 'Still' , NULL , NULL , NULL , NULL ),
    ( 453 , 308 , 309, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 456 , 309 , 310, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 459 , 311 , 312, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 462 , 312 , 313, 'Still' , NULL , NULL , NULL , NULL ),
    ( 465 , 313 , 314, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 468 , 315 , 316, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 471 , 316 , 317, 'Still' , NULL , NULL , NULL , NULL ),
    ( 474 , 317 , 318, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 477 , 318 , 319, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 480 , 319 , 320, 'Still' , NULL , NULL , NULL , NULL ),
    ( 483 , 321 , 322, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 486 , 322 , 323, 'Still' , NULL , NULL , NULL , NULL ),
    ( 489 , 323 , 324, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 492 , 324 , 325, 'Still' , NULL , NULL , NULL , NULL ),
    ( 495 , 326 , 327, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 498 , 327 , 328, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 501 , 328 , 329, 'Still' , NULL , NULL , NULL , NULL ),
    ( 504 , 329 , 330, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 507 , 330 , 331, 'Fwd' , NULL , $$Rotazione 180°$$ , NULL , NULL ),
    ( 510 , 332 , 333, 'Still' , NULL , NULL , NULL , NULL ),
    ( 513 , 333 , 334, 'Still' , NULL , NULL , NULL , NULL ),
    ( 516 , 334 , 335, 'Still' , NULL , NULL , NULL , NULL ),
    ( 519 , 336 , 337, 'Still' , NULL , NULL , NULL , NULL ),
    ( 522 , 340 , 341, 'Still' , NULL , NULL , NULL , NULL ),
    ( 525 , 456 , 457, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 526 , 457 , 458, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 527 , 458 , 459, 'Still' , NULL , NULL , NULL , NULL ),
    ( 528 , 459 , 460, 'Still' , NULL , NULL , NULL , NULL ),
    ( 531 , 466 , 467, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 532 , 467 , 468, 'Still' , NULL , NULL , NULL , NULL ),
    ( 533 , 468 , 469, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 534 , 469 , 470, 'Still' , NULL , NULL , NULL , NULL ),
    ( 537 , 476 , 477, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 538 , 477 , 478, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 539 , 478 , 479, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 540 , 479 , 480, 'Still' , NULL , NULL , NULL , NULL ),
    ( 543 , 486 , 487, 'Still' , NULL , NULL , NULL , NULL ),
    ( 544 , 487 , 488, 'Still' , NULL , $$Il braccio frontale resta avanzato$$ , NULL , NULL ),
    ( 547 , 496 , 497, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 548 , 497 , 498, 'Still' , NULL , NULL , NULL , NULL ),
    ( 549 , 498 , 499, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 550 , 499 , 500, 'Still' , NULL , NULL , NULL , NULL ),
    ( 553 , 506 , 507, 'Bkw' , NULL , NULL , NULL , NULL ),
    ( 554 , 507 , 508, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 555 , 508 , 509, 'Still' , NULL , NULL , NULL , NULL ),
    ( 556 , 509 , 510, 'Still' , NULL , NULL , NULL , NULL ),
    ( 559 , 516 , 517, 'Fwd' , NULL , NULL , NULL , NULL ),
    ( 560 , 517 , 518, 'Still' , NULL , NULL , NULL , NULL ),
    ( 563 , 526 , 527, 'Still' , NULL , NULL , NULL , NULL ),
    ( 564 , 527 , 528, 'Still' , NULL , NULL , NULL , NULL ),
    ( 565 , 528 , 529, 'Still' , NULL , NULL , NULL , NULL ),
    ( 566 , 529 , 530, 'Still' , NULL , NULL , NULL , NULL )
;

 
INSERT INTO ski.Kata_inventory(
    id_kata ,
    kata ,
    serie ,
    starting_leg ,
    notes , 
    resources, 
    resource_url
) VALUES 
    ( 1 , 'Heian Shodan' , 'Heian' , 'sx' , $$Primo kata$$ , $${"chiave":"valore","secondachiave":"secondo valore"}$$::jsonb , NULL ) ,
    ( 2 , 'Heian Nidan' , 'Heian' , 'sx' , NULL , NULL , NULL ) ,
    ( 3 , 'Heian Sandan' , 'Heian' , 'sx' , NULL , NULL , NULL ) ,
    ( 4 , 'Heian Yondan' , 'Heian' , 'sx' , NULL , NULL , NULL ) ,
    ( 5 , 'Heian Godan' , 'Heian' , 'sx' , NULL , NULL , NULL ) ,
    ( 6 , 'Bassai Dai' , 'Sentei' , 'dx' , NULL , NULL , NULL ) ,
    ( 7 , 'Kanku Dai' , 'Sentei' , 'sx' , NULL , NULL , NULL ) ,
    ( 8 , 'Jion' , 'Sentei' , 'frontal' , NULL , NULL , NULL ) ,
    ( 9 , 'Empi' , 'Sentei' , 'sx' , NULL , NULL , NULL ) 
;
 
INSERT INTO ski.kata_sequence(
    id_sequence ,
    kata_id ,
    seq_num ,
    stand_id ,
    speed, 
    side, 
    hips,
    embusen  ,
    facing ,
    kiai ,
    notes,
    remarks,
    resources,
    resource_url
) VALUES
    ( 1 , 1 , 0, 1 ,  'Fast'  ,  'frontal'  , NULL , (0,0) , 'N' , false , $$Preparare il piede destro$$ , ARRAY[ROW('Braccio SX', $$Parata$$, $$Uchi uke lascia passare l'attacco$$, $$Parata da un attacco$$)::public.detailednotes] , $${"chiave":"valore","secondachiave":"secondo valore"}$$::jsonb , NULL ) ,
    ( 2 , 1 , 1, 4 , NULL ,  'sx'  ,  'Hanmi'  , (0,0) , 'O' , false , NULL , NULL , NULL , NULL ) ,
    ( 3 , 1 , 2, 4 , NULL ,  'dx'  ,  'Shomen'  , (-1,0) , 'O' , false , $$braccio sinistro spinge verso destra per caricare la rotazione$$ , NULL , NULL , NULL ) ,
    ( 4 , 1 , 3, 4 , NULL ,  'dx'  , NULL , (-2,0) , 'E' , false , NULL , NULL , NULL , NULL ) ,
    ( 5 , 1 , 4, 16 , NULL ,  'dx'  , NULL , (0,0) , 'E' , false , NULL , NULL , NULL , NULL ) ,
    ( 6 , 1 , 5, 4 , NULL ,  'sx'  , NULL , (1,0) , 'E' , false , NULL , NULL , NULL , NULL ) ,
    ( 7 , 1 , 6, 4 , NULL ,  'sx'  , NULL , (0,0) , 'N' , false , NULL , NULL , NULL , NULL ) ,
    ( 8 , 1 , 7, 4 , NULL ,  'sx'  , NULL , (0,0) , 'N' , false , NULL , NULL , NULL , NULL ) ,
    ( 9 , 1 , 8, 4 , NULL ,  'dx'  , NULL , (0,1) , 'N' , false , NULL , NULL , NULL , NULL ) ,
    ( 10 , 1 , 9, 4 , NULL ,  'sx'  , NULL , (0,2) , 'N' , false , NULL , NULL , NULL , NULL ) ,
    ( 11 , 1 , 10, 4 , NULL ,  'dx'  , NULL , (0,3) , 'N' , true , NULL , NULL , NULL , NULL ) ,
    ( 12 , 1 , 11, 4 , NULL ,  'sx'  , NULL , (0,3) , 'E' , false , NULL , NULL , NULL , NULL ) ,
    ( 13 , 1 , 12, 4 , NULL ,  'dx'  , NULL , (1,3) , 'E' , false , NULL , NULL , NULL , NULL ) ,
    ( 14 , 1 , 13, 4 , NULL ,  'dx'  , NULL , (0,3) , 'O' , false , NULL , NULL , NULL , NULL ) ,
    ( 15 , 1 , 14, 4 , NULL ,  'sx'  , NULL , (-1,3) , 'O' , false , NULL , NULL , NULL , NULL ) ,
    ( 16 , 1 , 15, 4 , NULL ,  'sx'  , NULL , (0,3) , 'S' , false , NULL , NULL , NULL , NULL ) ,
    ( 17 , 1 , 16, 4 , NULL ,  'dx'  , NULL , (0,2) , 'S' , false , NULL , NULL , NULL , NULL ) ,
    ( 18 , 1 , 17, 4 , NULL ,  'sx'  , NULL , (0,1) , 'S' , false , NULL , NULL , NULL , NULL ) ,
    ( 19 , 1 , 18, 4 , NULL ,  'dx'  , NULL , (0,0) , 'S' , false , NULL , NULL , NULL , NULL ) ,
    ( 20 , 1 , 19, 5 , NULL ,  'sx'  , NULL , (0,0) , 'O' , false , NULL , NULL , NULL , NULL ) ,
    ( 21 , 1 , 20, 5 , NULL ,  'dx'  , NULL , (1,1) , 'NO' , false , NULL , NULL , NULL , NULL ) ,
    ( 22 , 1 , 21, 5 , NULL ,  'dx'  , NULL , (0,0) , 'E' , false , NULL , NULL , NULL , NULL ) ,
    ( 23 , 1 , 22, 5 , NULL ,  'sx'  , NULL , (1,1) , 'NE' , true , NULL , NULL , NULL , NULL ) ,
    ( 30 , 2 , 0, 1 , NULL ,  'frontal'  , NULL , (0,0) , 'N' , false , NULL , NULL , NULL , NULL ) ,
    ( 31 , 2 , 1, 5 , NULL ,  'sx'  , NULL , (-1,0) , 'O' , false , NULL , NULL , NULL , NULL ) ,
    ( 32 , 2 , 2, 5 , NULL ,  'sx'  , NULL , (-1,0) , 'O' , false , NULL , NULL , NULL , NULL ) ,
    ( 33 , 2 , 3, 5 , NULL ,  'sx'  , NULL , (-1,0) , 'O' , false , NULL , NULL , NULL , NULL ) ,
    ( 34 , 2 , 4, 5 , NULL ,  'dx'  , NULL , (0,0) , 'E' , false , NULL , NULL , NULL , NULL ) ,
    ( 35 , 2 , 5, 5 , NULL ,  'dx'  , NULL , (0,0) , 'E' , false , NULL , NULL , NULL , NULL ) ,
    ( 36 , 2 , 6, 5 , NULL ,  'dx'  , NULL , (0,0) , 'E' , false , NULL , NULL , NULL , NULL ) ,
    ( 37 , 2 , 7, 3 , NULL ,  'dx'  , NULL , (0,0) , 'S' , false , NULL , NULL , NULL , NULL ) ,
    ( 38 , 2 , 8, 5 , NULL ,  'sx'  , NULL , (0,-1) , 'N' , false , NULL , NULL , NULL , NULL ) ,
    ( 39 , 2 , 9, 5 , NULL ,  'dx'  , NULL , (0,0) , 'N' , false , NULL , NULL , NULL , NULL ) ,
    ( 40 , 2 , 10, 5 , NULL ,  'sx'  , NULL , (0,1) , 'N' , false , NULL , NULL , NULL , NULL ) ,
    ( 41 , 2 , 11, 4 , NULL ,  'dx'  , NULL , (0,2) , 'N' , true , NULL , NULL , NULL , NULL ) ,
    ( 42 , 2 , 12, 5 , NULL ,  'sx'  , NULL , (0,2) , 'E' , false , NULL , NULL , NULL , NULL ) ,
    ( 43 , 2 , 13, 5 , NULL ,  'dx'  , NULL , (-1,2) , 'SE' , false , NULL , NULL , NULL , NULL ) ,
    ( 44 , 2 , 14, 5 , NULL ,  'dx'  , NULL , (0,2) , 'O' , false , NULL , NULL , NULL , NULL ) ,
    ( 45 , 2 , 15, 5 , NULL ,  'sx'  , NULL , (0,2) , 'SO' , false , NULL , NULL , NULL , NULL ) ,
    ( 46 , 2 , 16, 4 , NULL ,  'sx'  , NULL , (0,2) , 'S' , false , NULL , NULL , NULL , NULL ) ,
    ( 47 , 2 , 17, 4 , NULL ,  'dx'  , NULL , (0,1) , 'S' , false , NULL , NULL , NULL , NULL ) ,
    ( 48 , 2 , 18, 4 , NULL ,  'dx'  , NULL , (0,1) , 'S' , false , NULL , NULL , NULL , NULL ) ,
    ( 49 , 2 , 19, 4 , NULL ,  'dx'  , NULL , (0,1) , 'S' , false , NULL , NULL , NULL , NULL ) ,
    ( 50 , 2 , 20, 4 , NULL ,  'sx'  , NULL , (0,0) , 'S' , false , NULL , NULL , NULL , NULL ) ,
    ( 51 , 2 , 21, 4 , NULL ,  'sx'  , NULL , (0,0) , 'S' , false , NULL , NULL , NULL , NULL ) ,
    ( 52 , 2 , 22, 4 , NULL ,  'dx'  , NULL , (0,-1) , 'S' , false , NULL , NULL , NULL , NULL ) ,
    ( 53 , 2 , 23, 4 , NULL ,  'sx'  , NULL , (-1,-1) , 'O' , false , NULL , NULL , NULL , NULL ) ,
    ( 54 , 2 , 24, 4 , NULL ,  'sx'  , NULL , (-1,-1) , 'NO' , false , NULL , NULL , NULL , NULL ) ,
    ( 55 , 2 , 25, 4 , NULL ,  'dx'  , NULL , (-1,0) , 'NO' , false , NULL , NULL , NULL , NULL ) ,
    ( 56 , 2 , 26, 4 , NULL ,  'dx'  , NULL , (-1,0) , 'E' , false , NULL , NULL , NULL , NULL ) ,
    ( 57 , 2 , 27, 4 , NULL ,  'dx'  , NULL , (-1,0) , 'NE' , false , NULL , NULL , NULL , NULL ) ,
    ( 58 , 2 , 28, 4 , NULL ,  'sx'  , NULL , (0,0) , 'NE' , true , NULL , NULL , NULL , NULL ) 
;

 
INSERT INTO ski.kata_sequence_waza (
    id_kswaza ,
    sequence_id ,
    arto ,
    technic_id ,
    strikingpart_id,
    technic_target_id,
    notes,
    resources
) VALUES
    ( 1 , 1 , ('Braccio',NULL) , 0, NULL , NULL ,$$Attesa dell' hajime$$ ,NULL ),
    ( 2 , 2 , ('Braccio','sx') , 19, NULL , 2 ,NULL ,NULL ),
    ( 3 , 3 , ('Braccio','dx') , 51, NULL , 2 ,NULL ,NULL ),
    ( 4 , 4 , ('Braccio','dx') , 19, NULL , 2 ,NULL ,NULL ),
    ( 5 , 5 , ('Braccio','dx') , 72, NULL , 2 ,NULL ,NULL ),
    ( 6 , 6 , ('Braccio','sx') , 51, NULL , 2 ,NULL ,NULL ),
    ( 7 , 7 , ('Braccio','sx') , 19, NULL , 2 ,NULL ,NULL ),
    ( 8 , 8 , ('Braccio','sx') , 85, NULL , 1 ,NULL ,NULL ),
    ( 9 , 9 , ('Braccio','dx') , 11, NULL , 1 ,NULL ,NULL ),
    ( 10 , 10 , ('Braccio','sx') , 11, NULL , 1 ,NULL ,NULL ),
    ( 11 , 11 , ('Braccio','dx') , 11, NULL , 1 ,NULL ,NULL ),
    ( 12 , 12 , ('Braccio','sx') , 19, NULL , 2 ,NULL ,NULL ),
    ( 13 , 13 , ('Braccio','dx') , 51, NULL , 2 ,NULL ,NULL ),
    ( 14 , 14 , ('Braccio','dx') , 19, NULL , 2 ,NULL ,NULL ),
    ( 15 , 15 , ('Braccio','sx') , 51, NULL , 2 ,NULL ,NULL ),
    ( 16 , 16 , ('Braccio','sx') , 19, NULL , 2 ,NULL ,NULL ),
    ( 17 , 17 , ('Braccio','dx') , 51, NULL , 2 ,NULL ,NULL ),
    ( 18 , 18 , ('Braccio','sx') , 51, NULL , 2 ,NULL ,NULL ),
    ( 19 , 19 , ('Braccio','dx') , 51, NULL , 2 ,NULL ,NULL ),
    ( 20 , 20 , ('Braccio','sx') , 58, NULL , 1 ,$$Devia un colpo$$ ,NULL ),
    ( 21 , 21 , ('Braccio','dx') , 57, NULL , 1 ,NULL ,NULL ),
    ( 22 , 22 , ('Braccio','dx') , 58, NULL , 1 ,NULL ,NULL ),
    ( 23 , 23 , ('Braccio','sx') , 57, NULL , 1 ,NULL ,NULL ),
    ( 24 , 30 , ('Braccio',NULL) , 0, NULL , NULL ,NULL ,NULL ),
    ( 25 , 31 , ('Braccio',NULL) , 21, NULL , NULL ,NULL ,NULL ),
    ( 26 , 32 , ('Braccio','dx') , 75, NULL , NULL ,$$Sotto la parata$$ ,NULL ),
    ( 27 , 32 , ('Braccio','sx') , 64, NULL , NULL ,NULL ,NULL ),
    ( 28 , 33 , ('Braccio','dx') , 30, NULL , NULL ,NULL ,NULL ),
    ( 29 , 33 , ('Braccio','sx') , 72, NULL , NULL ,NULL ,NULL ),
    ( 30 , 34 , ('Braccio',NULL) , 21, NULL , NULL ,NULL ,NULL ),
    ( 31 , 35 , ('Braccio','sx') , 75, NULL , NULL ,NULL ,NULL ),
    ( 32 , 35 , ('Braccio','dx') , 64, NULL , NULL ,NULL ,NULL ),
    ( 33 , 36 , ('Braccio','sx') , 30, NULL , NULL ,NULL ,NULL ),
    ( 34 , 36 , ('Braccio','dx') , 72, NULL , NULL ,NULL ,NULL ),
    ( 35 , 37 , ('Gamba','dx') , 82, NULL , NULL ,NULL ,NULL ),
    ( 36 , 37 , ('Braccio','dx') , 76, NULL , NULL ,NULL ,NULL ),
    ( 37 , 38 , ('Braccio','sx') , 58, NULL , NULL ,NULL ,NULL ),
    ( 38 , 39 , ('Braccio','dx') , 58, NULL , NULL ,NULL ,NULL ),
    ( 39 , 40 , ('Braccio','sx') , 57, NULL , NULL ,NULL ,NULL ),
    ( 40 , 41 , ('Braccio','dx') , 86, NULL , NULL ,NULL ,NULL ),
    ( 41 , 42 , ('Braccio','sx') , 58, NULL , NULL ,NULL ,NULL ),
    ( 42 , 43 , ('Braccio','dx') , 58, NULL , NULL ,NULL ,NULL ),
    ( 43 , 44 , ('Braccio','dx') , 58, NULL , NULL ,NULL ,NULL ),
    ( 44 , 45 , ('Braccio','sx') , 58, NULL , NULL ,NULL ,NULL ),
    ( 45 , 46 , ('Braccio','dx') , 73, NULL , NULL ,NULL ,NULL ),
    ( 46 , 47 , ('Gamba','dx') , 41, NULL , NULL ,NULL ,NULL ),
    ( 47 , 48 , ('Braccio','sx') , 14, NULL , NULL ,NULL ,NULL ),
    ( 48 , 49 , ('Braccio','dx') , 14, NULL , NULL ,$$Tsuki sul braccio sinistro per liberarsi da una presa$$ ,NULL ),
    ( 49 , 50 , ('Gamba','sx') , 41, NULL , NULL ,NULL ,NULL ),
    ( 50 , 51 , ('Braccio','dx') , 14, NULL , NULL ,NULL ,NULL ),
    ( 51 , 52 , ('Braccio',NULL) , 48, NULL , NULL ,NULL ,NULL ),
    ( 52 , 53 , ('Braccio','sx') , 19, NULL , NULL ,NULL ,NULL ),
    ( 53 , 54 , ('Braccio','sx') , 85, NULL , NULL ,NULL ,NULL ),
    ( 54 , 55 , ('Braccio','dx') , 11, NULL , NULL ,NULL ,NULL ),
    ( 55 , 56 , ('Braccio','dx') , 19, NULL , NULL ,NULL ,NULL ),
    ( 56 , 57 , ('Braccio','dx') , 85, NULL , NULL ,NULL ,NULL ),
    ( 57 , 58 , ('Braccio','sx') , 11, NULL , NULL ,NULL ,NULL )
;

 
INSERT INTO ski.kata_tx(
    id_tx ,
    from_sequence ,
    to_sequence ,
    tempo ,
    direction, 
    intermediate_stand_id,
    notes,
    remarks,
    resources,
    resource_url
) VALUES
    ( 1 , 1 , 2 , 'Fast' , 'sx' , NULL , $$Con piede destro già pronto prima abbassarsi alla quota corretta poi eseguire le parata$$ , ARRAY[ROW(('Braccio','sx'), $$Parata$$, $$Uchi uke lascia passare l'attacco$$, $$Parata da un attacco$$)::public.detailednotes] , $${"chiave":"valore","secondachiave":"secondo valore"}$$::jsonb , 'url' ),
    ( 2 , 2 , 3 , 'Fast' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 3 , 3 , 4 , 'Normal' , 'dx' , NULL , $$girare prima i piedi ed allungare il braccio sinistro per esprimere le rotazione$$ , NULL , NULL , NULL ),
    ( 4 , 4 , 5 , 'Slow' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 5 , 5 , 6 , 'Normal' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 6 , 6 , 7 , 'Normal' , 'sx' , NULL , NULL , NULL , NULL , NULL ),
    ( 7 , 7 , 8 , 'Slow' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 8 , 8 , 9 , 'Normal' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 9 , 9 , 10 , 'Normal' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 10 , 10 , 11 , 'Fast' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 11 , 11 , 12 , 'Normal' , 'sx' , NULL , NULL , NULL , NULL , NULL ),
    ( 12 , 12 , 13 , 'Fast' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 13 , 13 , 14 , 'Normal' , 'dx' , NULL , NULL , NULL , NULL , NULL ),
    ( 14 , 14 , 15 , 'Fast' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 15 , 15 , 16 , 'Slow' , 'sx' , NULL , NULL , NULL , NULL , NULL ),
    ( 16 , 16 , 17 , 'Normal' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 17 , 17 , 18 , 'Normal' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 18 , 18 , 19 , 'Fast' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 19 , 19 , 20 , 'Normal' , 'sx' , NULL , NULL , NULL , NULL , NULL ),
    ( 20 , 20 , 21 , 'Fast' , 'dx' , NULL , NULL , NULL , NULL , NULL ),
    ( 21 , 21 , 22 , 'Normal' , 'dx' , NULL , NULL , NULL , NULL , NULL ),
    ( 22 , 22 , 23 , 'Fast' , 'sx' , NULL , NULL , NULL , NULL , NULL ),
    ( 23 , 30 , 31 , 'Fast' , 'sx' , NULL , NULL , NULL , NULL , NULL ),
    ( 24 , 31 , 32 , 'Normal' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 25 , 32 , 33 , 'Legato' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 26 , 33 , 34 , 'Normal' , 'dx' , NULL , NULL , NULL , NULL , NULL ),
    ( 27 , 34 , 35 , 'Normal' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 28 , 35 , 36 , 'Legato' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 29 , 36 , 37 , 'Breath' , 'dx' , NULL , NULL , NULL , NULL , NULL ),
    ( 30 , 37 , 38 , 'Normal' , 'sx' , NULL , NULL , NULL , NULL , NULL ),
    ( 31 , 38 , 39 , 'Normal' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 32 , 39 , 40 , 'Normal' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 33 , 40 , 41 , 'Fast' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 34 , 41 , 42 , 'Normal' , 'sx' , NULL , NULL , NULL , NULL , NULL ),
    ( 35 , 42 , 43 , 'Fast' , 'dx' , NULL , NULL , NULL , NULL , NULL ),
    ( 36 , 43 , 44 , 'Normal' , 'dx' , NULL , NULL , NULL , NULL , NULL ),
    ( 37 , 44 , 45 , 'Fast' , 'sx' , NULL , NULL , NULL , NULL , NULL ),
    ( 38 , 45 , 46 , 'Breath' , 'sx' , NULL , $$Aprire le braccia per invitare il colpo, piede sinistro si porta in posizione per lo zenkutsudachi$$ , NULL , NULL , NULL ),
    ( 39 , 46 , 47 , 'Normal' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 40 , 47 , 48 , 'Normal' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 41 , 48 , 49 , 'Legato' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 42 , 49 , 50 , 'Normal' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 43 , 50 , 51 , 'Normal' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 44 , 51 , 52 , 'Normal' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 45 , 52 , 53 , 'Normal' , 'sx' , NULL , NULL , NULL , NULL , NULL ),
    ( 46 , 53 , 54 , 'Slow' , 'dx' , NULL , NULL , NULL , NULL , NULL ),
    ( 47 , 54 , 55 , 'Fast' , 'frontal' , NULL , NULL , NULL , NULL , NULL ),
    ( 48 , 55 , 56 , 'Normal' , 'dx' , NULL , NULL , NULL , NULL , NULL ),
    ( 49 , 56 , 57 , 'Slow' , 'sx' , NULL , NULL , NULL , NULL , NULL ),
    ( 50 , 57 , 58 , 'Fast' , 'frontal' , NULL , NULL , NULL , NULL , NULL )
;


INSERT 
INTO ski.bunkai_inventory (
    id_bunkai, 
    kata_id, 
    version, 
    name, 
    description, 
    notes, 
    resources, 
    resource_url
)
VALUES 
    ( 1 , 1 , 1 , $$applicazione Shodan$$ , $$Primo esempio applicativo$$ , $$Bunkai di esempio$$ , $${"chiave":"valore","secondachiave":"secondo valore"}$$::jsonb , NULL ),
    ( 2 , 2 , 1 , $$Applicazione Nidan$$ , $$Secondo esempio$$ , $$Bunkai di esempio$$ , $${"Spiegazione":"Ecco una spiegazione","Autore":"M° Capa di bomba"}$$::jsonb , NULL ),
    ( 3 , 2 , 2 , $$Applicazione Nidan due$$ , $$esempio aggiuntivo$$ , NULL , $${"Spiegazione":"Spiegato","info":"questo è un test"}$$::jsonb , NULL )
;

INSERT 
INTO ski.bunkai_sequences (
    id_bunkaisequence,
    bunkai_id, 
    kata_sequence_id, 
    description, 
    notes, 
    remarks, 
    resources, 
    resource_url
)
VALUES 
    ( 1 , 1 , 2 , $$Para avversario dll' interno$$ , NULL , NULL , $${"chiave":"valore","secondachiave":"secondo valore"}$$::jsonb , NULL ),
    ( 2 , 1 , 3 , $$Tsuki alla bocca dello stomaco$$ , NULL , NULL , NULL , NULL ),
    ( 3 , 2 , 31 , $$Parata$$ , NULL , NULL , NULL , NULL ),
    ( 4 , 2 , 32 , $$Parata e attacco$$ , NULL , ARRAY[
        ROW(('Braccio','sx'), $$Parata$$, $$Uchi uke lascia passare l'attacco$$, $$Parata da un attacco$$)::public.detailednotes,
        ROW(('Braccio','dx'), $$Offesa$$, $$Passando dall'' interno colpisce l''avversario$$, $$Attacco$$)::public.detailednotes] , NULL , NULL ),"
    ( 5 , 2 , 33 , $$Attacco$$ , NULL , NULL , NULL , NULL )
;

