INSERT INTO  ski.targets(id_target ,name ,original_name ,description,notes ) VALUES
    ( 1 , 'Jodan' ,$$Jodan$$ ,$$Alto$$ ,NULL ),
    ( 2 , 'Chudan' ,$$Chudan$$ ,$$Medio$$ ,$$Poco sopra l'ombelico$$ ),
    ( 3 , 'Gedan' ,$$Gedan$$ ,$$Basso$$ ,NULL ),
    ( 4 , 'Testa' ,$$Atama$$ ,NULL ,NULL ),
    ( 5 , 'Faccia' ,$$Kao$$ ,NULL ,NULL ),
    ( 6 , 'Mascella' ,$$Ago$$ ,NULL ,$$Lato del volto sulla mascella$$ ),
    ( 7 , 'Collo Laterale' ,$$Kubi$$ ,NULL ,NULL ),
    ( 8 , 'Gola' ,$$Nodo$$ ,NULL ,NULL ),
    ( 9 , 'Torace' ,$$Mune$$ ,NULL ,NULL )
;

INSERT INTO ski.strikingparts( id_part ,name ,translation ,description ) VALUES 
    ( 1 , 'Seiken' ,NULL ,$$Nocche indice e medio$$ ),
    ( 2 , 'Koshi' ,NULL ,$$Radice delle dita dei piedi con dita alzate$$ ),
    ( 3 , 'Empi' ,$$Gomito$$ ,$$Gomito$$ ),
    ( 4 , 'Hirabasami' ,NULL ,$$incavo mano pollice indice$$ ),
    ( 5 , 'Kumade' ,NULL ,$$palmo della mano$$ ),
    ( 6 , 'Teisho' ,NULL ,$$palmo della mano all' attaccatura con l'avambraccio$$ ),
    ( 7 , 'Gaiwan' ,NULL ,$$Avambraccio dal lato esterno / ulna$$ ),
    ( 8 , 'Naiwan' ,NULL ,$$Avambraccio dal lato interno / radio$$ ),
    ( 9 , 'Haiwan' ,NULL ,$$Avambraccio lato superiore$$ ),
    ( 10 , 'Huraken' ,NULL ,$$Esterno della mano$$ ),
    ( 11 , 'Keito' ,NULL ,$$Radice del police$$ ),
    ( 12 , 'Kakuto' ,NULL ,$$polso esterno$$ ),
    ( 13 , 'Tetsui' ,NULL ,$$parte bassa del pungo$$ ),
    ( 14 , 'Washide' ,NULL ,$$Punta delle dita unite come a raccogliere$$ ),
    ( 15 , 'Nakadaka Ken' ,NULL ,$$Medio leggermente fuoriuscito dal pugno$$ ),
    ( 16 , 'Ippon Ken' ,NULL ,$$Indice leggermente fuoriuscito dal pugno$$ ),
    ( 17 , 'Hihon Nukite' ,NULL ,$$Punta di indice e medio protesi$$ ),
    ( 18 , 'Hiraken' ,NULL ,$$Falange intermedia della mano$$ ),
    ( 19 , 'Ippon Nukite' ,NULL ,$$Punta dell'indice proteso$$ ),
    ( 20 , 'Haito' ,NULL ,$$esterno della falange del pollice$$ ),
    ( 21 , 'Haishu' ,NULL ,$$Palmo esterno mano$$ ),
    ( 22 , 'Shuto' ,NULL ,$$Mano a taglio$$ ),
    ( 23 , 'Nukite' ,NULL ,$$punta delle dita estese ed unite $$ ),
    ( 24 , 'Sune' ,NULL ,$$tibbia$$ ),
    ( 25 , 'Hiza' ,NULL ,$$Ginocchio$$ ),
    ( 26 , 'Kakato' ,NULL ,$$Tallone$$ ),
    ( 28 , 'Sokuto' ,NULL ,$$Esterno del piede$$ ),
    ( 29 , 'teisoku' ,NULL ,$$Palmo del piede$$ ),
    ( 30 , 'Tsumashi' ,NULL ,$$Dita del piede$$ ),
    ( 31 , 'Heisoku' ,NULL ,$$Dorso del piede$$ );


INSERT INTO ski.grades (id_grade,gtype,grade) VALUES 
    (1,'kyu',9),
    (2,'kyu',8),
    (3,'kyu',7),
    (4,'kyu',6),
    (5,'kyu',5),
    (6,'kyu',4),
    (7,'kyu',3),
    (8,'kyu',2),
    (9,'kyu',1),
    (10,'dan',1),
    (11,'dan',2),
    (12,'dan',3),
    (13,'dan',4),
    (14,'dan',5),
    (15,'dan',6),
    (16,'dan',7);


INSERT INTO ski.stands(id_stand ,name ,description ,illustration_url ,notes ) VALUES
    ( 1 ,'Heiko dachi' ,$$Posizione naturale a gambe divaricate e piedi paralleli (YOI)$$ ,NULL ,NULL ),
    ( 2 ,'Musubi dachi' ,$$Posizione naturale con talloni uniti e punte divaricate a 90° (nel saluto)$$ ,NULL ,NULL ),
    ( 3 ,'Heisoku dachi' ,$$Posizione naturale con piedi e talloni uniti$$ ,NULL ,NULL ),
    ( 4 ,'Zenkutsu dachi' ,$$Posizione frontale$$ ,NULL ,NULL ),
    ( 5 ,'Kokutsu dachi' ,$$Posizione basata sulla gamba posteriore$$ ,NULL ,'Peso 30% gamba anteriore e 70% al posteriore' ),
    ( 6 ,'Kiba dachi' ,$$Posizione del cavaliere$$ ,NULL ,NULL ),
    ( 7 ,'Shiko dachi' ,$$Posizione quadrata$$ ,NULL ,NULL ),
    ( 8 ,'Hangetsu dachi' ,$$Posizione a Mezza luna$$ ,NULL ,NULL ),
    ( 9 ,'Sochin dachi' ,$$Posizione consolidata$$ ,NULL ,'Detta anche Fudo dachi' ),
    ( 10 ,'Neko ashi dachi' ,$$Posizione a gatto$$ ,NULL ,NULL ),
    ( 11 ,'Sanchin dachi' ,$$Posizione a clessidra$$ ,NULL ,NULL ),
    ( 12 ,'Hachinoji dachi' ,$$Posizione naturale a gambe divaricate e punte divaricate a 90°$$ ,NULL ,NULL ),
    ( 13 ,'Hachiji dachi' ,$$Posizione naturale a gambe divaricate$$ ,NULL ,NULL ),
    ( 14 ,'UchiHachiji dachi' ,$$Posizione a gambe divaricate e punte dei piedi all'interno$$ ,NULL ,NULL ),
    ( 15 ,'Teiji dachi' ,$$Posizione naturale con i piedi a forma di T$$ ,NULL ,NULL ),
    ( 16 ,'Renoji dachi' ,$$Posizione naturale con i piedi a forma di L$$ ,NULL ,NULL )
;


INSERT INTO ski.technics(id_technic,waza ,name ,description ,notes ,resource_url ) VALUES
    ( 0 , NULL ,'Yoi',$$Posizione neutra ma pronta$$ ,$$Posizione di partenza neutra ma pronta per l'azione$$ ,NULL ),
    ( 1 , NULL ,'Guardia',$$$$ ,NULL ,NULL ),
    ( 2 , NULL ,'Kiri Kaeshi',$$Cambio guardia$$ ,NULL ,NULL ),
    ( 10 , 'Uchi' ,'Age tsuki',$$Pugno diritto che sale dal basso verso l'alto$$ ,NULL ,NULL ),
    ( 11 , 'Uke' ,'Age uke',$$Parata crescente verso l'alto$$ ,NULL ,NULL ),
    ( 12 , 'Geri' ,'Ashi barai',$$Spazzata$$ ,NULL ,NULL ),
    ( 13 , 'Uchi' ,'Awase tsuki',$$Pugni a U piccola (eseguiti colpendo contemporaneamente il bersaglio alto con Choku tsuki e quello medio con Ura tsuki)$$ ,NULL ,NULL ),
    ( 14 , 'Uchi' ,'Chodan tsuki',$$Pugno sferrato verso la parte media del corpo dell'avversario$$ ,NULL ,NULL ),
    ( 15 , 'Uchi' ,'Choku tsuki',$$Pugno frontale sul posto$$ ,NULL ,NULL ),
    ( 16 , 'Uchi' ,'Enpi Uchi',$$Colpo di gomito$$ ,NULL ,NULL ),
    ( 17 , 'Geri' ,'Fumikiri',$$Calcio tagliente verso il basso$$ ,$$eseguito come uno YOKO GERI KEKOMI portato molto in basso: tibia, piede dell'avversario$$ ,NULL ),
    ( 18 , 'Geri' ,'Fumikomi',$$Calcio pressante (eseguito con una traiettoria dall'alto verso il basso, trasferendo tutto il peso del corpo sul piede che colpisce)$$ ,NULL ,NULL ),
    ( 19 , 'Uke' ,'Gedan barai',$$Parata verso il basso$$ ,NULL ,NULL ),
    ( 20 , 'Uke' ,'Gedan Kake uke',$$Parata bassa uncinante (eseguita facendo compiere all'avambraccio un ampio movimento dall'esterno verso l'interno; normalmente è usata per parare un MAEGERI)$$ ,NULL ,NULL ),
    ( 21 , 'Uchi' ,'Gedan tsuki',$$Pugno sferrato verso la parte bassa dell'avversario$$ ,NULL ,NULL ),
    ( 22 , 'Geri' ,'Gyaku mawashi geri',$$Calcio circolare contrario (è una variante del Mawashi geri, eseguito con traiettoria dall'interno verso l'esterno)$$ ,NULL ,NULL ),
    ( 23 , 'Uchi' ,'Gyaku tsuki',$$Pugno contrario (rispetto alla gamba avanzata)$$ ,NULL ,NULL ),
    ( 24 , 'Uke' ,'Haishu jkji uke',$$Parata con le mani a X (eseguita con le mani aperte ed i polsi uniti)$$ ,NULL ,NULL ),
    ( 25 , 'Uke' ,'Haishu uke',$$Parata con il dorso della mano$$ ,NULL ,NULL ),
    ( 26 , 'Uchi' ,'Haito Uchi',$$Colpo con la mano a coltello (eseguita colpendo con la parte interna del dorso della mano)$$ ,NULL ,NULL ),
    ( 27 , 'Uke' ,'Haiwan nagashi uke',$$Parata deviante con la parte esterna dell'avambraccio (eseguita spostando il braccio in avanti per intercettare l'attacco e deviandone la traiettoria)$$ ,NULL ,NULL ),
    ( 28 , 'Uchi' ,'Hasami tsuki',$$Pugni a forbice (eseguiti con un movimento degli arti in modo ampio e circolare, dall'esterno verso l'interno)$$ ,NULL ,NULL ),
    ( 29 , 'Geri' ,'Hiza geri',$$Ginocchiata$$ ,NULL ,NULL ),
    ( 30 , 'Uchi' ,'Jodan tsuki',$$Pugno sferrato verso il volto dell'avversario (zona tra naso e occhi)$$ ,NULL ,NULL ),
    ( 31 , 'Uke' ,'Juji uke',$$Parata a due mani ad X (effettuata con pugni chiusi e polsi uniti)$$ ,NULL ,NULL ),
    ( 32 , 'Uchi' ,'Kagi tsuki',$$Pugno a uncino (eseguito formando con il braccio un angolo di 90°)$$ ,NULL ,NULL ),
    ( 33 , 'Geri' ,'Kakato geri',$$Calcio con il tallone (eseguita facendo scendere il tallone dall'alto, dopo avere caricato il calcio lanciando la gamba verso l'alto)$$ ,NULL ,NULL ),
    ( 34 , 'Uke' ,'Kakiwake uke',$$Parata a due mani a cuneo rovesciato$$ ,NULL ,NULL ),
    ( 35 , 'Uke' ,'Kakuto uke',$$Parata con il polso a testa di gru$$ ,NULL ,NULL ),
    ( 36 , 'Uke' ,'Keito uke',$$Parata con la mano a testa di gallina$$ ,NULL ,NULL ),
    ( 37 , 'Geri' ,'Kizami Geri',$$$$ ,NULL ,NULL ),
    ( 38 , 'Uchi' ,'Kizami tsuki',$$Pugno anteriore (eseguito lanciando il pugno, corrispondente alla gamba avanzata, verso il bersaglio; il piede potrà rimanere fermo o essere spostato in avanti)$$ ,NULL ,NULL ),
    ( 39 , 'Uchi' ,'Mae Empi ',$$$$ ,NULL ,NULL ),
    ( 40 , 'Uchi' ,'Mae Enpi Uchi',$$Colpo di gomito frontale (eseguita sul piano orizzontale)$$ ,NULL ,NULL ),
    ( 41 , 'Geri' ,'Mae geri',$$Calcio frontale$$ ,NULL ,NULL ),
    ( 42 , 'Geri' ,'Mae tobi geri',$$Calcio volante frontale$$ ,NULL ,NULL ),
    ( 43 , 'Uchi' ,'Mawashi Enpi Uchi',$$Colpo di gomito circolare$$ ,NULL ,NULL ),
    ( 44 , 'Geri' ,'Mawashi geri',$$Calcio circolare$$ ,NULL ,NULL ),
    ( 45 , 'Uchi' ,'Mawashi tsuki',$$Pugno circolare$$ ,NULL ,NULL ),
    ( 46 , 'Geri' ,'Mikatsuki geri',$$Calcio a luna crescente (eseguito con una traiettoria circolare crescente dal suolo sino al bersaglio)$$ ,NULL ,NULL ),
    ( 47 , 'Uchi' ,'Morote tsuki',$$Colpo portato simultaneamente con due pugni$$ ,NULL ,NULL ),
    ( 48 , 'Uke' ,'Morote uke',$$Parata a due mani rinforzata$$ ,NULL ,NULL ),
    ( 49 , 'Geri' ,'Nidan geri',$$Calcio volante doppio (eseguito lanciando due MAE GERI in successione alternata mentre si è in elevazione; il primo colpisce al livello Chudan, il secondo, con l'altra gamba, a livello Jodan)$$ ,NULL ,NULL ),
    ( 50 , 'Uchi' ,'Nihon Nukite',$$$$ ,NULL ,NULL ),
    ( 51 , 'Uchi' ,'Oi tsuki',$$Pugno lungo$$ ,NULL ,NULL ),
    ( 52 , 'Uchi' ,'Otoshi Enpi Uchi',$$Colpo di gomito dall'alto verso il basso$$ ,NULL ,NULL ),
    ( 53 , 'Uke' ,'Otoshi uke',$$Parata discendente (eseguita facendo scendere l'avambraccio perpendicolarmente sull'avambraccio dell'avversario)$$ ,NULL ,NULL ),
    ( 54 , 'Geri' ,'Ren geri',$$Calcio alternato (eseguito lanciando due MAE GERI in successione alternata)$$ ,NULL ,NULL ),
    ( 55 , 'Uchi' ,'Sanbon tsuki',$$Combinazione di tre pugni (generalmente il primo è Jodan, gli altri due Chudan)$$ ,NULL ,NULL ),
    ( 56 , 'Uke' ,'Seirykto uke',$$Parata con la mano a spada cinese$$ ,NULL ,NULL ),
    ( 57 , 'Uchi' ,'Shuto Uchi',$$Colpo con la mano a coltello (eseguita colpendo con la parte esterna del dorso della mano)$$ ,NULL ,NULL ),
    ( 58 , 'Uke' ,'Shuto uke',$$Parata con il taglio della mano$$ ,NULL ,NULL ),
    ( 59 , 'Uke' ,'Sokumen awase uke',$$Parata laterale a due mani (eseguita utilizzando il palmo della mano che è rafforzata dal dorso dell'altra)$$ ,NULL ,NULL ),
    ( 60 , 'Uke' ,'Sokumen Haito Uke',$$$$ ,NULL ,NULL ),
    ( 61 , 'Uke' ,'Sokutei mawashi uke',$$Parata circolare con la pianta del piede$$ ,NULL ,NULL ),
    ( 62 , 'Uke' ,'Sokutei osae uke',$$Parata pressante con la pianta del piede (eseguita per fermare con molto anticipo un calcio che è ancora nella fase di caricamento)$$ ,NULL ,NULL ),
    ( 63 , 'Uke' ,'Sokuto osae uke',$$Parata pressante con il taglio del piede$$ ,NULL ,NULL ),
    ( 64 , 'Uke' ,'Soto Ude uke',$$Parata media eseguita con la parte esterna dell'avambraccio$$ ,NULL ,NULL ),
    ( 65 , 'Uchi' ,'Tate Enpi Uchi',$$Colpo di gomito frontale portato dal basso verso l'alto$$ ,NULL ,NULL ),
    ( 66 , 'Uke' ,'Tate Shuto uke',$$Parata con il taglio della mano verticale$$ ,NULL ,NULL ),
    ( 67 , 'Uke' ,'Te Nagashi uke',$$Parata deviante con la mano (eseguita intercettando il braccio dell'attaccante e deviandone la traiettoria con il palmo della propria mano).$$ ,NULL ,NULL ),
    ( 68 , 'Uke' ,'Te osae uke',$$Parata con la mano pressante (eseguita portando la propria mano ad intercettare l'avambraccio dell'attaccante, abbassandolo e tirandolo all'indietro, provocando lo sbilanciamento in avanti dell'avversario).$$ ,NULL ,NULL ),
    ( 69 , 'Uke' ,'Teisho awase uke',$$Parata con le basi dei palmi delle due mani (eseguita tenendo a contatto i polsi)$$ ,NULL ,NULL ),
    ( 70 , 'Uchi' ,'Teisho Uchi',$$Colpo con la base del palmo della mano$$ ,NULL ,NULL ),
    ( 71 , 'Uke' ,'Teisho uke',$$Parata con la base del palmo della mano$$ ,NULL ,NULL ),
    ( 72 , 'Uchi' ,'Tettsui Uchi',$$Colpo col pugno a martello$$ ,NULL ,NULL ),
    ( 73 , 'Uke' ,'Uchi Ude uke',$$Parata media eseguita con la parte interna dell'avambraccio$$ ,NULL ,NULL ),
    ( 74 , 'Geri' ,'Ura mawashi geri',$$Calcio circolare rovesciato$$ ,NULL ,NULL ),
    ( 75 , 'Uchi' ,'Ura tsuki',$$Pugno rovesciato (eseguito colpendo dal basso verso l'alto e arrivando al bersaglio con il palmo verso l'alto)$$ ,NULL ,NULL ),
    ( 76 , 'Uchi' ,'Uraken Uchi',$$Colpo col dorso del pugno$$ ,NULL ,NULL ),
    ( 77 , 'Uchi' ,'Ushiro Enpi Uchi',$$Colpo di gomito all'indietro$$ ,NULL ,NULL ),
    ( 78 , 'Geri' ,'Ushiro geri',$$Calcio all'indietro$$ ,NULL ,NULL ),
    ( 79 , 'Geri' ,'Ushiro mawashi geri',$$Calcio all'indietro circolare$$ ,NULL ,NULL ),
    ( 80 , 'Uchi' ,'Yama tsuki',$$Pugni a U larga$$ ,NULL ,NULL ),
    ( 81 , 'Uchi' ,'Yoko Enpi Uchi',$$Colpo di gomito laterale$$ ,NULL ,NULL ),
    ( 82 , 'Geri' ,'Yoko geri Keage',$$Calcio laterale frustato$$ ,NULL ,NULL ),
    ( 83 , 'Geri' ,'Yoko geri Kekomi',$$Calcio laterale spinto$$ ,NULL ,NULL ),
    ( 84 , 'Geri' ,'Yoko Tobi geri',$$Calcio volante laterale$$ ,NULL ,NULL ),
    ( 85 , 'Uke' ,'Age Shuto Uke',$$Parata a taglio verso l'alto (movimento che si fa con la mano opposta quando si esegue Age uke da studio)$$ ,NULL ,NULL ),
    ( 200 , NULL ,'Shi Ho Soto Uke Gyakuzuki',$$Quattro direzioni$$ ,NULL ,NULL ),
    ( 250 , NULL ,'Kime Waza',$$Controllo$$ ,NULL ,NULL )
;


INSERT INTO ski.kihon_inventory(id_inventory ,grade_id ,number ) VALUES
    ( 1 ,'1' ,'1' ),
    ( 2 ,'1' ,'2' ),
    ( 3 ,'1' ,'3' ),
    ( 4 ,'1' ,'4' ),
    ( 5 ,'1' ,'5' ),
    ( 6 ,'1' ,'6' ),
    ( 7 ,'1' ,'7' ),
    ( 8 ,'1' ,'8' ),
    ( 9 ,'1' ,'9' ),
    ( 10 ,'1' ,'10' ),
    ( 11 ,'2' ,'1' ),
    ( 12 ,'2' ,'2' ),
    ( 13 ,'2' ,'3' ),
    ( 14 ,'2' ,'4' ),
    ( 15 ,'2' ,'5' ),
    ( 16 ,'2' ,'6' ),
    ( 17 ,'2' ,'7' ),
    ( 18 ,'2' ,'8' ),
    ( 19 ,'2' ,'9' ),
    ( 20 ,'2' ,'10' ),
    ( 21 ,'3' ,'1' ),
    ( 22 ,'3' ,'2' ),
    ( 23 ,'3' ,'3' ),
    ( 24 ,'3' ,'4' ),
    ( 25 ,'3' ,'5' ),
    ( 26 ,'3' ,'6' ),
    ( 27 ,'3' ,'7' ),
    ( 28 ,'3' ,'8' ),
    ( 29 ,'3' ,'9' ),
    ( 30 ,'3' ,'10' ),
    ( 31 ,'4' ,'1' ),
    ( 32 ,'4' ,'2' ),
    ( 33 ,'4' ,'3' ),
    ( 34 ,'4' ,'4' ),
    ( 35 ,'4' ,'5' ),
    ( 36 ,'4' ,'6' ),
    ( 37 ,'4' ,'7' ),
    ( 38 ,'4' ,'8' ),
    ( 39 ,'4' ,'9' ),
    ( 40 ,'4' ,'10' ),
    ( 41 ,'5' ,'1' ),
    ( 42 ,'5' ,'2' ),
    ( 43 ,'5' ,'3' ),
    ( 44 ,'5' ,'4' ),
    ( 45 ,'5' ,'5' ),
    ( 46 ,'5' ,'6' ),
    ( 47 ,'5' ,'7' ),
    ( 48 ,'5' ,'8' ),
    ( 49 ,'5' ,'9' ),
    ( 50 ,'5' ,'10' ),
    ( 51 ,'6' ,'1' ),
    ( 52 ,'6' ,'2' ),
    ( 53 ,'6' ,'3' ),
    ( 54 ,'6' ,'4' ),
    ( 55 ,'6' ,'5' ),
    ( 56 ,'6' ,'6' ),
    ( 57 ,'6' ,'7' ),
    ( 58 ,'6' ,'8' ),
    ( 59 ,'6' ,'9' ),
    ( 60 ,'6' ,'10' ),
    ( 61 ,'7' ,'1' ),
    ( 62 ,'7' ,'2' ),
    ( 63 ,'7' ,'3' ),
    ( 64 ,'7' ,'4' ),
    ( 65 ,'7' ,'5' ),
    ( 66 ,'7' ,'6' ),
    ( 67 ,'7' ,'7' ),
    ( 68 ,'7' ,'8' ),
    ( 69 ,'7' ,'9' ),
    ( 70 ,'7' ,'10' ),
    ( 71 ,'8' ,'1' ),
    ( 72 ,'8' ,'2' ),
    ( 73 ,'8' ,'3' ),
    ( 74 ,'8' ,'4' ),
    ( 75 ,'8' ,'5' ),
    ( 76 ,'8' ,'6' ),
    ( 77 ,'8' ,'7' ),
    ( 78 ,'8' ,'8' ),
    ( 79 ,'8' ,'9' ),
    ( 80 ,'8' ,'10' ),
    ( 81 ,'9' ,'1' ),
    ( 82 ,'9' ,'2' ),
    ( 83 ,'9' ,'3' ),
    ( 84 ,'9' ,'4' ),
    ( 85 ,'9' ,'5' ),
    ( 86 ,'9' ,'6' ),
    ( 87 ,'9' ,'7' ),
    ( 88 ,'9' ,'8' ),
    ( 89 ,'9' ,'9' ),
    ( 90 ,'9' ,'10' ),
    ( 91 ,'10' ,'1' ),
    ( 92 ,'10' ,'2' ),
    ( 93 ,'10' ,'3' ),
    ( 94 ,'10' ,'4' ),
    ( 95 ,'10' ,'5' ),
    ( 96 ,'10' ,'6' ),
    ( 97 ,'10' ,'7' ),
    ( 98 ,'10' ,'8' ),
    ( 99 ,'10' ,'9' ),
    ( 100 ,'10' ,'10' ),
    ( 101 ,'11' ,'1' ),
    ( 102 ,'11' ,'2' ),
    ( 103 ,'11' ,'3' ),
    ( 104 ,'11' ,'4' ),
    ( 105 ,'11' ,'5' ),
    ( 106 ,'11' ,'6' ),
    ( 107 ,'11' ,'7' ),
    ( 108 ,'11' ,'8' ),
    ( 109 ,'11' ,'9' ),
    ( 110 ,'11' ,'10' ),
    ( 111 ,'12' ,'1' ),
    ( 112 ,'12' ,'2' ),
    ( 113 ,'12' ,'3' ),
    ( 114 ,'12' ,'4' ),
    ( 115 ,'12' ,'5' ),
    ( 116 ,'12' ,'6' ),
    ( 117 ,'12' ,'7' ),
    ( 118 ,'12' ,'8' ),
    ( 119 ,'12' ,'9' ),
    ( 120 ,'12' ,'10' )
;


INSERT INTO ski.kihon_sequences(id_sequence, inventory_id , seq_num,stand,techinc,gyaku,target_hgt,notes,resource_url) VALUES 
    ( 456 ,91 ,0,4 , 1 ,'false' ,NULL , NULL , NULL ),
    ( 457 ,91 ,1,4 , 70 ,'false' ,'Chudan' , NULL , NULL ),
    ( 458 ,91 ,2,4 , 11 ,'true' ,'Chudan' , NULL , NULL ),
    ( 459 ,91 ,3,4 , 26 ,'false' ,'Chudan' , NULL , NULL ),
    ( 460 ,91 ,4,4 , 40 ,'false' ,'Chudan' , NULL , NULL ),
    ( 466 ,92 ,0,4 , 1 ,'false' ,NULL , NULL , NULL ),
    ( 467 ,92 ,1,4 , 36 ,'false' ,'Chudan' , NULL , NULL ),
    ( 468 ,92 ,2,9 , 52 ,'false' ,'Chudan' , NULL , NULL ),
    ( 469 ,92 ,3,4 , 64 ,'false' ,'Chudan' , NULL , NULL ),
    ( 470 ,92 ,4,4 , 76 ,'true' ,'Jodan' , NULL , NULL ),
    ( 476 ,93 ,0,4 , 1 ,'false' ,NULL , NULL , NULL ),
    ( 477 ,93 ,1,4 , 34 ,'false' ,'Chudan' , NULL , NULL ),
    ( 478 ,93 ,2,4 , 80 ,'false' ,'Chudan' , NULL , NULL ),
    ( 479 ,93 ,3,4 , 29 ,'false' ,'Chudan' , NULL , NULL ),
    ( 480 ,93 ,4,4 , 65 ,'false' ,'Chudan' , NULL , NULL ),
    ( 486 ,94 ,0,4 , 1 ,'false' ,NULL , NULL , NULL ),
    ( 487 ,94 ,1,4 , 2 ,'false' ,'Chudan' , $$Il braccio del lato che è davanti deve essere proteso con il pugno formando una leggera curvatura.$$ , NULL ),
    ( 488 ,94 ,2,9 , 15 ,'false' ,'Chudan' , $$Il braccio che era davanti resta in posizione avanzata formando una protezione, mantre viene sferrato il pugno.$$ , NULL ),
    ( 496 ,95 ,0,4 , 1 ,'false' ,NULL , NULL , NULL ),
    ( 497 ,95 ,1,4 , 35 ,'false' ,'Chudan' , NULL , NULL ),
    ( 498 ,95 ,2,4 , 14 ,'false' ,'Chudan' , NULL , NULL ),
    ( 499 ,95 ,3,4 , 18 ,'false' ,'Chudan' , NULL , NULL ),
    ( 500 ,95 ,4,4 , 50 ,'false' ,'Jodan' , NULL , NULL ),
    ( 506 ,96 ,0,4 , 1 ,'false' ,NULL , NULL , NULL ),
    ( 507 ,96 ,1,4 , 73 ,'false' ,'Chudan' , NULL , NULL ),
    ( 508 ,96 ,2,4 , 78 ,'false' ,'Chudan' , NULL , NULL ),
    ( 509 ,96 ,3,6 , 50 ,'false' ,'Chudan' , NULL , NULL ),
    ( 510 ,96 ,4,4 , 32 ,'false' ,'Chudan' , NULL , NULL ),
    ( 516 ,97 ,0,4 , 1 ,'false' ,NULL , NULL , NULL ),
    ( 517 ,97 ,1,4 , 83 ,'false' ,'Chudan' , NULL , NULL ),
    ( 518 ,97 ,2,4 , 41 ,'false' ,'Chudan' , NULL , NULL ),
    ( 526 ,98 ,0,4 , 1 ,'false' ,NULL , NULL , NULL ),
    ( 527 ,98 ,1,4 , 37 ,'false' ,'Chudan' , NULL , NULL ),
    ( 528 ,98 ,2,4 , 38 ,'false' ,'Chudan' , NULL , NULL ),
    ( 529 ,98 ,3,4 , 41 ,'false' ,'Chudan' , NULL , NULL ),
    ( 530 ,98 ,4,4 , 23 ,'false' ,'Chudan' , NULL , NULL ),
    ( 537 ,99 ,1,4 , 200 ,'false' ,'Chudan' , NULL , NULL ),
    ( 541 ,100 ,1,4 , 250 ,'false' ,'Chudan' , NULL , NULL )
;


INSERT INTO ski.kihon_tx(id_tx ,from_seq ,to_seq ,movement ,notes ,resource_url ) VALUES
    ( 455 , 456 , 457, 'Fwd' , NULL , NULL ),
    ( 456 , 457 , 458, 'Bkw' , NULL , NULL ),
    ( 457 , 458 , 459, 'Still' , NULL , NULL ),
    ( 458 , 459 , 460, 'Still' , NULL , NULL ),
    ( 465 , 466 , 467, 'Fwd' , NULL , NULL ),
    ( 466 , 467 , 468, 'Still' , NULL , NULL ),
    ( 467 , 468 , 469, 'Fwd' , NULL , NULL ),
    ( 468 , 469 , 470, 'Still' , NULL , NULL ),
    ( 475 , 476 , 477, 'Bkw' , NULL , NULL ),
    ( 476 , 477 , 478, 'Fwd' , NULL , NULL ),
    ( 477 , 478 , 479, 'Fwd' , NULL , NULL ),
    ( 478 , 479 , 480, 'Still' , NULL , NULL ),
    ( 485 , 486 , 487, 'Still' , NULL , NULL ),
    ( 486 , 487 , 488, 'Still' , $$Il braccio frontale resta avanzato$$ , NULL ),
    ( 495 , 496 , 497, 'Bkw' , NULL , NULL ),
    ( 496 , 497 , 498, 'Still' , NULL , NULL ),
    ( 497 , 498 , 499, 'Fwd' , NULL , NULL ),
    ( 498 , 499 , 500, 'Still' , NULL , NULL ),
    ( 505 , 506 , 507, 'Bkw' , NULL , NULL ),
    ( 506 , 507 , 508, 'Fwd' , NULL , NULL ),
    ( 507 , 508 , 509, 'Still' , NULL , NULL ),
    ( 508 , 509 , 510, 'Still' , NULL , NULL ),
    ( 515 , 516 , 517, 'Fwd' , NULL , NULL ),
    ( 525 , 526 , 527, 'Still' , NULL , NULL ),
    ( 526 , 527 , 528, 'Still' , NULL , NULL ),
    ( 527 , 528 , 529, 'Still' , NULL , NULL ),
    ( 528 , 529 , 530, 'Still' , NULL , NULL )
;

 


INSERT INTO ski.Kata_inventory(
    id_kata ,
    kata ,
    serie ,
    starting_leg ,
    notes
) VALUES 
    ( 1 , 'Heian Shodan' , 'Heian' , 'sx' , $$Primo kata$$ ) ,
    ( 2 , 'Heian Nidan' , 'Heian' , 'sx' , NULL ) ,
    ( 3 , 'Heian Sandan' , 'Heian' , 'sx' , NULL ) ,
    ( 4 , 'Heian Yondan' , 'Heian' , 'sx' , NULL ) ,
    ( 5 , 'Heian Godan' , 'Heian' , 'sx' , NULL ) ,
    ( 6 , 'Bassai Dai' , 'Sentei' , 'dx' , NULL ) ,
    ( 7 , 'Kanku Dai' , 'Sentei' , 'sx' , NULL ) ,
    ( 8 , 'Jion' , 'Sentei' , 'frontal' , NULL ) ,
    ( 9 , 'Empi' , 'Sentei' , 'sx' , NULL )
;

INSERT INTO ski.kata_sequence(
    id_sequence ,
    kata_id ,
    seq_num ,
    stand_id ,
    side ,
    embusen  ,
    facing ,
    kiai ,
    notes
) VALUES
    ( 1 , 1 , 0, 1 ,  'frontal'  , (0,0) , 'N' , false ,  'Preparare il piede destro'  ) ,
    ( 2 , 1 , 1, 4 ,  'sx'  , (0,0) , 'O' , false , NULL ) ,
    ( 3 , 1 , 2, 4 ,  'dx'  , (-1,0) , 'O' , false ,  'braccio sinistro spinge verso destra per caricare la rotazione'  ) ,
    ( 4 , 1 , 3, 4 ,  'dx'  , (-2,0) , 'E' , false , NULL ) ,
    ( 5 , 1 , 4, 16 ,  'dx'  , (0,0) , 'E' , false , NULL ) ,
    ( 6 , 1 , 5, 4 ,  'sx'  , (1,0) , 'E' , false , NULL ) ,
    ( 7 , 1 , 6, 4 ,  'sx'  , (0,0) , 'N' , false , NULL ) ,
    ( 8 , 1 , 7, 4 ,  'sx'  , (0,0) , 'N' , false , NULL ) ,
    ( 9 , 1 , 8, 4 ,  'dx'  , (0,1) , 'N' , false , NULL ) ,
    ( 10 , 1 , 9, 4 ,  'sx'  , (0,2) , 'N' , false , NULL ) ,
    ( 11 , 1 , 10, 4 ,  'dx'  , (0,3) , 'N' , true , NULL ) ,
    ( 12 , 1 , 11, 4 ,  'sx'  , (0,3) , 'E' , false , NULL ) ,
    ( 13 , 1 , 12, 4 ,  'dx'  , (1,3) , 'E' , false , NULL ) ,
    ( 14 , 1 , 13, 4 ,  'dx'  , (0,3) , 'O' , false , NULL ) ,
    ( 15 , 1 , 14, 4 ,  'sx'  , (-1,3) , 'O' , false , NULL ) ,
    ( 16 , 1 , 15, 4 ,  'sx'  , (0,3) , 'S' , false , NULL ) ,
    ( 17 , 1 , 16, 4 ,  'dx'  , (0,2) , 'S' , false , NULL ) ,
    ( 18 , 1 , 17, 4 ,  'sx'  , (0,1) , 'S' , false , NULL ) ,
    ( 19 , 1 , 18, 4 ,  'dx'  , (0,0) , 'S' , false , NULL ) ,
    ( 20 , 1 , 19, 5 ,  'sx'  , (0,0) , 'O' , false , NULL ) ,
    ( 21 , 1 , 20, 5 ,  'dx'  , (1,1) , 'NO' , false , NULL ) ,
    ( 22 , 1 , 21, 5 ,  'dx'  , (0,0) , 'E' , false , NULL ) ,
    ( 23 , 1 , 22, 5 ,  'sx'  , (1,1) , 'NE' , true , NULL ) 
;


INSERT INTO ski.kata_sequence_waza (
    sequence_id ,
    arto ,
    technic_id ,
    technic_target_id,
    notes
) VALUES
    ( 1 , 'Braccia' , 0, NULL ,$$Attesa dell' hajime$$ ),
    ( 2 , 'Braccio SX' , 19, 2 ,NULL ),
    ( 3 , 'Braccio DX' , 51, 2 ,NULL ),
    ( 4 , 'Braccio DX' , 19, 2 ,NULL ),
    ( 5 , 'Braccio DX' , 72, 2 ,NULL ),
    ( 6 , 'Braccio SX' , 51, 2 ,NULL ),
    ( 7 , 'Braccio SX' , 19, 2 ,NULL ),
    ( 8 , 'Braccio SX' , 85, 1 ,NULL ),
    ( 9 , 'Braccio DX' , 11, 1 ,NULL ),
    ( 10 , 'Braccio SX' , 11, 1 ,NULL ),
    ( 11 , 'Braccio DX' , 11, 1 ,NULL ),
    ( 12 , 'Braccio SX' , 19, 2 ,NULL ),
    ( 13 , 'Braccio DX' , 51, 2 ,NULL ),
    ( 14 , 'Braccio DX' , 19, 2 ,NULL ),
    ( 15 , 'Braccio SX' , 51, 2 ,NULL ),
    ( 16 , 'Braccio SX' , 19, 2 ,NULL ),
    ( 17 , 'Braccio DX' , 51, 2 ,NULL ),
    ( 18 , 'Braccio SX' , 51, 2 ,NULL ),
    ( 19 , 'Braccio DX' , 51, 2 ,NULL ),
    ( 20 , 'Braccio SX' , 58, 1 ,$$Devia un colpo$$ ),
    ( 21 , 'Braccio DX' , 57, 1 ,NULL ),
    ( 22 , 'Braccio DX' , 58, 1 ,NULL ),
    ( 23 , 'Braccio SX' , 57, 1 ,NULL )
;

INSERT INTO ski.kata_tx(
    --id_tx ,
    from_seq ,
    to_seq ,
    tempo ,
    direction,
    notes 
) VALUES
    ( 1 , 2 , 'Fast' , 'sx' , $$Con piede destro già pronto prima abbassarsi alla quota corretta poi eseguire le parata$$ ),
    ( 2 , 3 , 'Fast' , 'frontal' , NULL ),
    ( 3 , 4 , 'Normal' , 'dx' , $$girare prima i piedi ed allungare il braccio sinistro per esprimere le rotazione$$ ),
    ( 4 , 5 , 'Slow' , 'frontal' , NULL ),
    ( 5 , 6 , 'Normal' , 'frontal' , NULL ),
    ( 6 , 7 , 'Normal' , 'sx' , NULL ),
    ( 7 , 8 , 'Slow' , 'frontal' , NULL ),
    ( 8 , 9 , 'Normal' , 'frontal' , NULL ),
    ( 9 , 10 , 'Normal' , 'frontal' , NULL ),
    ( 10 , 11 , 'Fast' , 'frontal' , NULL ),
    ( 11 , 12 , 'Normal' , 'sx' , NULL ),
    ( 12 , 13 , 'Fast' , 'frontal' , NULL ),
    ( 13 , 14 , 'Normal' , 'dx' , NULL ),
    ( 14 , 15 , 'Fast' , 'frontal' , NULL ),
    ( 15 , 16 , 'Slow' , 'sx' , NULL ),
    ( 16 , 17 , 'Normal' , 'frontal' , NULL ),
    ( 17 , 18 , 'Normal' , 'frontal' , NULL ),
    ( 18 , 19 , 'Fast' , 'frontal' , NULL ),
    ( 19 , 20 , 'Normal' , 'sx' , NULL ),
    ( 20 , 21 , 'Fast' , 'dx' , NULL ),
    ( 21 , 22 , 'Normal' , 'dx' , NULL ),
    ( 22 , 23 , 'Fast' , 'sx' , NULL )
;












